- platform: command_line
  switches:
    # PC commands
    family_room_monitor_on_off:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?monitor_on_off"
    family_room_pc_volume_up:
      friendly_name: PC Volume Up
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?volume_up"
    family_room_pc_volume_down:
      friendly_name: PC Volume Down
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?volume_down"
    family_room_pc_volume_mute:
      friendly_name: PC Volume Mute
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?volume_mute"
    #Keyboard Commands
    family_room_pc_direction_up:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?up"
    family_room_pc_direction_down:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?down"
    family_room_pc_direction_left:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?left"
    family_room_pc_direction_right:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?right"
    family_room_pc_page_up:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?page_up"
    family_room_pc_page_down:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?page_down"
    family_room_pc_home:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?home"
    family_room_pc_end:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?end"
    family_room_pc_enter:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?enter"
    family_room_pc_escape:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?escape"
    family_room_pc_tab:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?tab"
    #Mouse Commands
    family_room_mouse_up:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_up"
    family_room_mouse_down:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_down"
    family_room_mouse_left:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_left"
    family_room_mouse_right:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_right"
    family_room_mouse_up_move:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_up_move"
    family_room_mouse_down_move:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_down_move"
    family_room_mouse_left_move:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_left_move"
    family_room_mouse_right_move:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_right_move"
    family_room_mouse_scroll_up:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_scroll_up"
    family_room_mouse_scroll_down:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_scroll_down"
    family_room_mouse_scroll_up_page:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_scroll_up_page"
    family_room_mouse_scroll_down_page:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_scroll_down_page"
    family_room_mouse_click:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?mouse_click"
    #Plex Commands
    # Plex PC commands
    family_room_plex:
      friendly_name: Plex
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_start"
      command_off: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_quit"
    family_room_plex_active:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_active"
    family_room_plex_fullscreen:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_fullscreen"
    family_room_plex_home:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_home"
    family_room_plex_home_back:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_home_back"
    family_room_plex_info:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_info"
    family_room_plex_search:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_search"
    family_room_plex_play:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_play"
    family_room_plex_stop:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_stop"
    family_room_plex_pause:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_pause"
    family_room_plex_fastforward:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_fastforward"
    family_room_plex_rewind:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_rewind"
    family_room_plex_menu:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_menu"
    family_room_plex_context_menu:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_context_menu"
    family_room_plex_subtitles:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_subtitles"
    family_room_plex_subtitles_next:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?plex_subtitles_next"
    #Bell Commands
    family_room_bell:
      friendly_name: Bell
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_start"
      command_off: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_quit"
    family_room_bell_active:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_active"
    family_room_bell_channel0:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel0"
    family_room_bell_channel1:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel1"
    family_room_bell_channel2:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel2"
    family_room_bell_channel3:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel3"
    family_room_bell_channel4:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel4"
    family_room_bell_channel5:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel5"
    family_room_bell_channel6:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel6"
    family_room_bell_channel7:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel7"
    family_room_bell_channel8:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel8"
    family_room_bell_channel9:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_channel9"
    family_room_bell_command0:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command0"
    family_room_bell_command1:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command1"
    family_room_bell_command2:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command2"
    family_room_bell_command3:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command3"
    family_room_bell_command4:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command4"
    family_room_bell_command5:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command5"
    family_room_bell_command6:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command6"
    family_room_bell_command7:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command7"
    family_room_bell_command8:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command8"
    family_room_bell_command9:
      command_on: "/usr/bin/curl -k http://192.168.1.101:8099/?bell_command9"
