#Toggle light group templates
- platform: template
  switches:
    entrance_way_lights:
      value_template: '{{ is_state("group.entrance_way_lights", "on") }}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.entrance_way_lights
      turn_off: 
        service: homeassistant.turn_off
        entity_id: group.entrance_way_lights
    bedroom_lights:
      value_template: '{{ is_state("group.bedroom_lights", "on") }}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.bedroom_lights
      turn_off: 
        service: homeassistant.turn_off
        entity_id: group.bedroom_lights
    family_room_light:
      value_template: '{{ is_state("group.family_room_light", "on") }}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.family_room_light
      turn_off: 
        service: homeassistant.turn_off
        entity_id: group.family_room_light
    family_room_lights:
      value_template: '{{ is_state("group.family_room_lights", "on") }}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.family_room_lights
      turn_off: 
        service: homeassistant.turn_off
        entity_id: group.family_room_lights
    theatre_lights:
      value_template: '{{ is_state("group.theatre_lights", "on") }}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.theatre_lights
      turn_off: 
        service: homeassistant.turn_off
        entity_id: group.theatre_lights
    dining_room_lights:
      value_template: '{{ is_state("group.dining_room_lights", "on") }}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.dining_room_lights
      turn_off: 
        service: homeassistant.turn_off
        entity_id: group.dining_room_lights
