homeassistant:
  auth_providers:
    - type: homeassistant
  name: !secret hass_name # Name of the location where Home Assistant is running
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric # metric for Metric, imperial for Imperial
  country: CA
  time_zone: America/Toronto
  customize: !include_dir_merge_named customize/ # Customization files
  customize_glob: !include_dir_merge_named customize_glob/
  packages: !include_dir_named packages
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes/
system_health:
config: # Enables configuration UI
mobile_app: #integration allows Home Assistant mobile apps to easily integrate with Home Assistant
ios: !include ios.yaml
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
recorder: !include recorder.yaml
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
logger:
  default: error
  #default: info
  #default: debug
  # logs:
  #   homeassistant.components.websocket_api: debug #fatal
map: # Enables a map showing the location of tracked devices
sun: # Track the sun
media_source: #may be a bug since 2022.5 as should be loaded automatically
# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_client_secret
google_assistant: !include google_assistant.yaml
camera: !include cameras.yaml

#yaml configuration files
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list sensors_binary/
device_tracker: !include device_trackers.yaml
group: !include_dir_merge_named groups/
input_boolean: !include_dir_merge_named inputs/boolean/
input_datetime: !include_dir_merge_named inputs/datetime/
input_number: !include_dir_merge_named inputs/number/
input_select: !include_dir_merge_named inputs/select/
input_text: !include_dir_merge_named inputs/text/
light: !include_dir_merge_list lights/
media_player: !include_dir_merge_list media_players/
mqtt:
  sensor: !include_dir_merge_list mqtt/sensor/
  binary_sensor: !include_dir_merge_list mqtt/binary_sensor/
  switch: !include_dir_merge_list mqtt/switch/
notify: !include notify.yaml
rest_command: !include_dir_merge_named rest_commands/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
timer: !include_dir_merge_named timers/
tplink:
  discovery: false
  switch:
    - host: 192.168.1.30 #deck lights
    - host: 192.168.1.31 #bedroom light
    - host: 192.168.1.32 #sink light
  dimmer:
    - host: 192.168.1.33 #kale ceiling light
tts: # Text to speech
  - platform: google_translate
    service_name: google_say
    cache: false

#UI configuration items
#iRobot - 192.168.1.50 username: 3173C71442408660 password: :1:1609091352:IeeeTtgkc2z3t2cH
#to regenerate run-> docker run -it node sh -c "npm install -g dorita980 && get-roomba-password 192.168.1.50"
lovelace:
  mode: yaml #Enable yaml config for lovelace
  resources:
    # HACS TRACKED CARDS (community)
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js
      type: module
    - url: /hacsfiles/Home-Assistant-Lovelace-Local-Conditional-card/local-conditional-card.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity-row/battery-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-more-info-card/more-info-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-text-input-row/lovelace-text-input-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/radial-menu/radial-menu.js
      type: module
    - url: /hacsfiles/search-card/search-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/text-action-element/text-action-element-bundle.js
      type: module
    - url: /hacsfiles/text-divider-row/text-divider-row.js
      type: module
    - url: /hacsfiles/text-action-element/text-action-element.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
