- platform: plex_recently_added
  token: !secret plex_media_server_token
  host: 192.168.1.12
  port: 32400
  ssl: false
  ssl_cert: false
  download_images: false
  max: 5
  section_types:
    - movie
    - show
