title: !secret hass_name_lovelace

views: #If changes made in !include file, a change must be made in this file to reflect changes in !include file (they are not checked for changes)
  - !include /config/lovelace/views/home.yaml #default view Home
  - !include /config/lovelace/views/dashboard.yaml #Home Dashboard (Tablet) view
  - !include /config/lovelace/views/rooms/bedroom.yaml #Rooms
  - !include /config/lovelace/views/rooms/family_room.yaml
  - !include /config/lovelace/views/rooms/theatre.yaml
  - !include /config/lovelace/views/other/thermostat.yaml #other views
  - !include /config/lovelace/views/other/sensors.yaml
  - !include /config/lovelace/views/other/cameras.yaml
  - !include /config/lovelace/views/remotes/r.family_room.yaml #television remotes
  - !include /config/lovelace/views/remotes/r.dining_room.yaml
  - !include /config/lovelace/views/remotes/r.theatre.yaml
  - !include /config/lovelace/views/remotes/r.bedroom.yaml
  - !include /config/lovelace/views/other/settings.yaml
  - !include /config/lovelace/views/other/settings_admin.yaml
  - !include /config/lovelace/views/other/settings_locks.yaml

kiosk_mode: !include lovelace/includes/kiosk_mode.yaml
decluttering_templates: !include lovelace/includes/decluttering_templates.yaml
button_card_templates: !include lovelace/includes/button_card_templates.yaml
