## Broadlink RM Mini 3 Family Room s/n RM0 -  ip: 192.168.1.82
- platform: broadlink
  mac: '34:EA:34:58:B7:11'
  switches:
    #Denon Amp (Family Room) IR commands    
    - name: Family Room Surround Sound
      command_on:
        'JgCqAAoYDDkJGQsXCxgJOwoYCRoKGAoZCToLOgs5ChgLGAgABZ4MFwo6CxgIGgsXChkJOws5CTsLOQwXCRkLFwo7CTsLAAWcChgLOgkZCxgJGAw5CxcKGAsXChkKOgs6CDwLFwoZCQAFnggaCzkLGAkZChgKGAs5CzoIPAs5ChkKGAsXCjoMOAwABZsMFwo6CxcLGAoYCjsJGQsXChkJGQo6CjoKOgwXCRkLAA0FAAAAAAAAAAAAAAAAAAA='
      command_off:
        'JgCqAAkaCzkJGQsXCxgJGQo6CRoKGAsYCTsLOQs5CBoLGAgABZ4MFwo6CxgJGQsXCjsJGQs5CjoIPAwXChgLFws6CTsLAAWcCxcLOggaCxgIGgsXCjoKGAwXCRkKOgs6Bz0LFwoZCQAFnggaCzkLGAkZChgKOgsXCzoJOws5ChkKGAsYCToKOwsABZwLFwo6DBcKGAoYChkJOwsXChkJGQo6CTsKOgwXCRkLAA0FAAAAAAAAAAAAAAAAAAA='      
    - name: Family Room Surround Sound Volume Up
      command_on:
        'JgDIAAkaCD0IGgkaCBoJPAkaCBoIGwc+CTwJPAk9CxgKGAsABc4MFghhChgHGwgbBz4JggoYCRoIGgkaCD0GPwcABdMIGgo7CxgHHAcbCjsLGAcbChkJPAo7CjsLOwYbCBsHAAXTChgLOgoZCxcLGAoYBz4JPQs6ChkJGQsXCxgGPws7CgAFzgkbCjsLFwsYChkKOgoZChkJGQo7CjsJPAk8CRoIGgkABdEJGgs6CBoKGQsXBxwHPgg9CD4KGAsXCxgGHAc+CjwKAA0F'      
    - name: Family Room Surround Sound volume_down
      command_on:
        'JgDMAAwXCzsJGQoYCxgKGAs6CxgKGAs7CjsKOwo7CxgKGAsABc8LGAo7CxcLGAoYCjsLGAo7CjsKGQoYCxgKGAs6CjsLAAXPCxcMOQsYCxgKGAsYCjsKGAsYCjsKPAk8CjsKGAoZCQAF0AsYCjsMFwkZChkJPAoYCjsLOgsYCxgKGAsYCTwKOwoABc8MFww5ChkKGAsYChgLOgoZChgLOgs6CzsKOwoZCRkKAAXPDBgJPAoYChkJGQo7ChkJPAo7ChkKGAkaCRkJPAs6CgANBQAAAAAAAAAAAAAAAA=='
    - name: Family Room Surround Sound Volume Mute
      command_on:
        'JgCqAAccBj4IGggbCBoGHQYcCBoGHQc9Bj8HPQg9BR0HHAcABaMIGgY/CBoIGgccBz4FPwc+CDwGHAccBR0HGwg9BT8HAAWkBxsIPQUdBxwHGwcbCBsFHQccCDwHPQc+BT8HGwgbBgAFpQYcBz0HHAUdBxwHPQc9CD0FPwccBxsHGwccBj4HPQkABaIHHAU/BxsIGwUdBxwJGQcbBxwFPwc+CTsHPQgbBhwHAA0FAAAAAAAAAAAAAAAAAAA='    
    - name: Family Room Surround Sound TV
      command_on:
        'JgDCAAxcCRoKgAcbC10HGwtdDDkHGwsYCwAF8QkaDDkJGQsYCxgKGAs6Bz4KGQo8CTwJGQgbBz4JPAgABa4MGAk8CRkJGgkZCTwKGQkZCTwKGQkZCTwJPAwXCxgKAAXyChgMOQkaCxgKGAsYCjsKOwoYCzoLOwoZCRgLOwo7CgAFrQoYDDoLGAkZCRkLOwoYCRkLOwoYCRoJPAo7CxgJGQkABfMKGQw5ChkKGAsYChgHPgs6ChkKOwo7CRkLGAs7CjsKAA0FAAAAAAAA'      
    - name: Family Room Surround Sound HDMI1
      command_on:
        'JgAMAQsYCTwLFwsYCxcLOgoZCjsKPAkZCxcKPAk8ChkKGAoABc8LGAs6CxgKGQoYCRoKOwkZCRoKOwo7CBoLGAk8CD0IAAXSChgMOQwXChgLGAs6CxcJPAw5CxgLGAo7CD4KGAgbBwAF0QsYDDoKGAgbChgKGAs7ChgLFws7CjsKGQoYCjsKOwsABc8MFwo7CxcJGgoYCTwJGgk8CzoJGgoYCTwKPAsXBxsHAAXTChkKOwoYCxgLFwoZCzoJGQsYCzoLOwkZChgKgQkABdEGHAo7CxgHHAkZCTwLGAk8CjsKGAccBz4KOwoYCBsHAAXTChgLOgccChgLGAoYCzoKGQoZCjoHPgccCxgKOwoADQUAAAAAAAAAAAAAAAA='      
    - name: Family Room Surround Sound HDMI2
      command_on:
        'JgAQAQsYCzoLGAkZChgLGAo8CTwJPAoYChkJPAo7ChgLGAsABc8LFww5DBcLFwsYCTwKGQoYCxgJPAo7ChgLGAo7CjsKAAXPDBcMOQwXChgLGAoYCzoLOwo7CxgJGQo7CjsLGAsYCQAFzwoaCjsKGAoZCRkKOwoZCRkKGQk8CTwLGAoYCjsKOwoABdALGAo7ChgKGQoYChkKOwo7CjwKGAoYCjwJPAkZChkJAAXQCxgKOwoZCRkKGQk8CRoJGQkaCTwJPAoYChkJPAo7CgAFzwkaCjsKGQkZChkJGQo7CTwKOwoZChgKPAk8CRoJGQkABdAKGQo8CRkJGQoZCTwKGQkZCRkKPAk8CRoJGQk8CTwKAA0FAAAAAAAAAAA='

    #*** NOT USED replaced with EventGhost ## PC IR Codes
    # family_room_ir_pc_direction_up:
    #   command_on:
    #     'JgDSAFkcEAwPDg8dDx0tGxAMDw8PDg8ODg8OEA4ODw4QDhANHQ4PDxANDg8OHhANDg8ODx0dEA0OEBAMDw4dDw8ODw4PHhAACMhWHhANDhAQGxAbLRsOEBAMDhANEBEMDRAQDREMDhAQDBwREAwNEBAODR4QDQ0REAsdHxEKDxANEBAOGxANEBANDh4QAAjIVh8QDQ0QDR4QGyseEQwNERANDRAPDhANDRAQDQ0REAwcEBAMEgwODxAcEQwNEA0QIBsQDBAODRANEB8NDRAQDRAcEA=='
    # family_room_ir_pc_direction_down:
    #   command_on:
    #     'JgDSAFceEAwPDg4eEBstHBANDg8NDw8PDw4ODw4QDg4PDg8OIAwPDg8ODx0RDA8PDg8ODxweEQwPDg4QDg4dDw4PEQwPDg8ACNlYHBANDg8OHhAbLRsRDA4QEAwPDg8OEgwPDg4PDhAODh0PDhANDxEbEA0ODw0QDREfGxAMDhAQDQ0QHw0NEBANDREQAAjXWBsRDQ8ODxwQHCwdEAwRDBANEA4PDRANEA4QDRANDw4fDQ8ODw4PHRAMEQwRDRANHh0QDBEMEQwRDR4NEA0QDg8ODw=='
    # family_room_ir_pc_direction_left:
    #   command_on:
    #     'JgDSAFgcEA0NEBAcEBstGxANDREQDQ0PEQ0NEA0QEA0RDA4PHw0NERAMDRAQHBEMDRAQDhsfEA0NEBANHB8QDA4PEA4QDQ0ACMxWHhANDRANHhAbLRwRDA4PDg8RDA8ODw4OEBANDRANERwPDg8ODxEMDR8QDQ8ODg8dHhAMDw4PDx0dEAwSDA8ODRAOAAjMVxwRDA0QEBwQHC0bEAwOEBANDRAQDg0QDQ8RDA0RDRAfDA0REAwOEBAcEA0NDxENHxsQDQ4QEAwcHxANDRAQDQ4PEQ=='
    # family_room_ir_pc_direction_right:
    #   command_on:
    #     'JgDMAFYfEAwOEBAbEBstHBANDRANEQ0PDg8NEBENDRAQDA4QHQ4PDg8PDh4QDA8PDg8ODxweEQwPDg4QHR0QDQ8ODg8dAAjaVxwQDRANEBwQGy0bEQwRDRANDw4PDhANEA0QDhANDw4eDREMEQwRHBAMEQwRDBAOHxsQDREMEA0fHBAMEQwRDR8ACNdYHBANEA0QGxAcLRwQDBEMEA4PDg8NEA0QDhANEA0PDx4NEA0PDw8cEAwRDRANEA0eHRAMEQwRDR4cEA4PDRANHg=='
    # family_room_ir_pc_mouse_up:
    #   command_on:
    #     'JgCKALQUCgoKCQsJeQoKCgoVExUKCAsKCgoKCgoKCgweCQsJFhMeCR8AAWi3Ex0JCwkpCgoJCwkLCQsJCwkLFRIWRgkLCQsJCwkLCQsJFxMKCAsKCgoNAAFmbwkLCQsJFhMKCQsJPQkLCQsJCwkLCSETFBUJCQsJCwkLCQsJCwkLCQsJKRUdCQsJDQANBQAAAAAAAAAAAAAAAAAA'
    # family_room_ir_pc_mouse_down:
    #   command_on:
    #     'JgD0AG4LPhMJCSgMMhQJCgoKCgoKCigVCQwJCYMKCgoKCgoKCgoTAAF0txMICwkKEwwzFAgLCQoKCwkMEgsJFwkJWgsJCwkLCgoKCgoKCgoKChYAAXGWChcSCQsJChMMHQoKFQkMTgoKFgoJCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoMEgABdW0KCgoKChYTCQoKCigKCgoKFgcNCQkLCQsJFAwJFQkKCgoeCgoKCgoKCgoKCgwKCAwIDAgMCBQAAXS1FHgVBwwKCVEVCQlwCQsJCg0ICQsJCg0nAAFythMeCFEVCQplFQkJMwwJCAwJCgwcDWIADQUAAAAA'
    # family_room_ir_pc_mouse_left:
    #   command_on:
    #     'JgDAALcSHA0bDRsNEhWMCTUUEgkNFE4NCBUJAAFpgQ0mFQcNCAwIDFETCQp4CjUTKRMJCicNGxYJAAFpbiAHDBQVCQl7EwkJRyBREyYWCQonIAwSCQABamwgJxUKCXkVCAwIDAgMCAwIDAgMJyAHFyYWCQkVCTYTCwABZ7MVbQ0UExwgCAxPDBwVKhJmEwwAAWezFTEgHA0TFMkTKRRkFAwAAWa3E4wUiwk1FCgUZBQLAAFotRMIDHgUyRQoFWQTDAANBQAAAAAAAAAA'
    # family_room_ir_pc_mouse_right:
    #   command_on:
    #     'JgC6AIEgExUHDQgMCAwmDRsWCQpuIAgMCAwVExIWCQoWEwkKNQABZm4NGw0UEgoJUCAIFgkJMw0bDRsgCAwUFBIWCQoWE0gAAWZtDQgKCgoUFY4THQwcDBwNYxQUFAgLFBUxDQkAAWizFQkKPAo1ExwgCAwJCnkUFRMJDRQTCAwIDAgMCAABa7MVHQ1kEwcOxhYSFikTCAwIDAkKDQABZrUVBwwIDAgMOw0IFQgLqwkVFRMVBw0TFQkKMwANBQAAAAAAAAAAAAAAAAAA'
    # family_room_ir_pc_mouse_click:
    #   command_on:
    #     'JgB8ALYTCCAIDAgMCAwnFggKvyAHDAgMTxYJCQ0ACbVtCgoKCgoXEwgLCQoKCgoMJgoKFwcMRQsJCwkLCQsKCgoKCgoKCgoKCgooCgoKChYHDQoACbW3EwgKCgoKCgoLCQoTDAkWCAsJDJULCgoKCgoKCgoTDB0KChUJDAoADQUAAAAAAAAAAAAAAAA='
    # family_room_ir_pc_pageup:
    #   command_on:
    #     ''
    # family_room_ir_pc_pagedown:
    #   command_on:
    #     ''
    # family_room_ir_pc_home:
    #   command_on:
    #     'JgCIAG4IGBIzCAwIDAgYEigVHggMCAwIDAgMCAwKKxIqEhQVHggMCAwIDAgMCAwIDAoLAAmKjBUJCmUVKhIJCqEWCQoUFRYSrQAJiW8IFhRFCioUEwoKFQkKCgoeDAgMCQsJCwkLFhIqExMVHQoeCwkMCAwJCgoKCgAKN4sVCQsJDJUMlQyVDJUADQU='
    # family_room_ir_pc_end:
    #   command_on:
    #     'JgB2AI0VCQkzCzwJIRMJCwkLjBYJCRUJDBQTFQkLCQsKCgoKCgoKCgoKCgAJjG0LExYdCh4KHgsTCwoKChUdCh4LHgoeChQVPhMTFR0KCgwJCQsKHgoKAAmMixaLCiETCQqhFScKDRMSFgkKhgAKM4wVCQoAApEADQUAAA=='