- platform: template
  switches:
    bedroom_tv_poweron:
      turn_on:
        - service: remote.send_command
          target:
            entity_id: remote.rm_pro_br_remote
          data:
            device: bedroom_tv
            command: power
      turn_off:
        - service: media_player.turn_off
          target:
            entity_id: media_player.bedroom_tv
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.bedroom_tv
    bedroom_tv:
      value_template: "{{ is_state('input_boolean.bedroom_tv', 'on') }}"
      turn_on:
        - service: switch.turn_on
          data_template:
            entity_id: "{% if is_state('input_boolean.bedroom_tv', 'off') %}switch.bedroom_tv_poweron{% else %}switch.null{% endif %}"
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.bedroom_tv
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.bedroom_tv_poweron

## Broadlink RM Pro Bedroom s/n RM0 -  ip: 192.168.1.81
- platform: broadlink
  mac: "34:EA:34:D0:AB:B1"
  switches:
    - name: Jalynne Bedroom Light
      command_on: "6RRGAN8JCRYWCRYJFgkJFgkWFgkJFgkWCRYJFhYJFgkWCQkWCRYWCRYJFgkWCQkWCRYWCQkWFgkJFhYJCRYWCQkWFgkWCQkAAUg="
      command_off: "6RRGAN8JFgkWCQkWFgkJFgkWFgkWCRYJFgkWCQkWCRYJFgkWFgkWCRYJFgkWCRYJFgkWCQkWFgkJFgkWCRYWCQkWFgkWCQkAAUg="
    - name: Jalynne Bedroom Fan
      command_on: "6RRGAN8JFgkWCRYJCRYWCRYJCRYJFgkWCRYWCRYJFgkWCQkWFgkWCRYJFgkJFhYJFgkJFgkWCRYWCQkWFgkJFhYJCRYJFgkAAUg="
      command_off: "6RRGAN8JCRYJFhYJCRYWCRYJCRYJFhYJCRYWCRYJFgkWCQkWFgkWCRYJCRYWCRYJFgkWCQkWCRYJFhYJFgkJFhYJFgkJFgkAAUg="

    #IR codes bedroom TV
    #Don't use Bedroom TV powertoggle implicitely (use template switch switch.bedroom_tv) as on/off toggle switch turns TV on if all switches being turned off turns off ir_sharp_tv:
    - name: Bedroom TV powertoggle
      command_on: "JgBYAAABJpMSExEUEhMRFBEUEjcRFBEUETgROBI3ETgSOBEUEDkROBEUEjcRFBEUETgSExE4ERQROBEUETgRORITETgRFBE4EgAFHgABJkkRAAxOAAEmSRIADQU="
    - name: Bedroom TV Input
      command_on: "JgBYAAABJZQSExITEhMSExITEjcSExITETgSNxI3ETgSNxITETkSNxITERQRFBEUEhISExE5ERQROBI3EjcSNxI3EjcSExE5EgAFHgABJkkSAAxNAAEmSRIADQU="
    - name: Bedroom TV Up
      command_on: "JgBYAAABJZMSExEUERQRFBITETgRFBEUETgROBE4ETkROBEUEjcROBE4EjcSOBITERQRExE5ERQRFBEUEBUROBI3ETgRFBE4EgAFHwABJUoRAAxOAAEmSRIADQU="
    - name: Bedroom TV Down
      command_on: "JgBYAAABJpMRFBAUERQRFBEUETgRFBITETkSNxE4ETgSNxEUEjcSOBE4EhMSNxI3EhMSExI3EhMSExI3ERQSExI3EjcSExI4EgAFHgABJkkSAAxNAAElShIADQU="
    - name: Bedroom TV Left
      command_on: "JgBYAAABJZMRFBITERQRFBEUEjcSExEUETgSNxI4EjcSNxITETgSNxE4ERQRFBE4EhMSExI4ERMTEhE5ETgRFBE4ETgSExE4EQAFIAABJUoSAAxNAAEmSREADQU="
    - name: Bedroom TV Right
      command_on: "JgBYAAABJpMSExEUERQRFBEUETgRFBITETgROBE4EjcROBITEjgROBE4ETgRFBE4EhMRFBE4EhMRFBITEjcSExI3EjgRFBE4EQAFHwABJUoRAAxPAAElShIADQU="
    - name: Bedroom TV OK
      command_on: "JgBQAAABJpISExEUERQRFBEUEjcRFBEUEjcSOBE4EjcSNxITEjcROBEUETkQFBE5ERQRFBE4EhMROBEUETgRFBE4EjcRFBE4EgAFHwABJkkSAA0FAAAAAAAAAAA="
    - name: Bedroom TV Menu
      command_on: "JgBYAAABJpISExEUERQRFBITEjcSExITETgTNhM3EjcSNxITETgSNxITEjcSOBITERQSExEUERMSOBITERQROBI3EjcSNxI3EgAFHwABJkkSAAxNAAElShEADQU="
    - name: Bedroom TV Exit
      command_on: "JgBYAAABJpISExITEhMSExEUEjcRFBEUETgRORE4EjcSNxITETgSNxEUEjgRFBE4EhMSExEUERQROBEUETgSExE4ETgSNxI4EQAFHwABJUoRAAxPAAElShIADQU="
    - name: Bedroom TV Info
      command_on: "JgBgAAABJpISExEUERQSExITETgSExITETgSNxI4ETgSNxEUETgSNxI3EjgSNxI3EhMRFBITERQSExITERQSEhI4EjcSNxI3EQAFIAABJkkSAAxOAAEmSRIADE4AASZJEgANBQAAAAAAAAAA"
    - name: Bedroom TV EPG
      command_on: "JgBgAAABJZMSExEUERQSExITETgSExITEjcSNxI4EjcSNxITEjcSNxITEhMSExI3ERQSExI3EhMSNxI3EjgSExI3EjcSExE4EgAFHgABJkkSAAxNAAEmSRIADEwAASZJEQANBQAAAAAAAAAA"
    - name: Bedroom TV Display
      command_on: "JgBYAAABJpISExITEhMSExEUETgSExITETgSNxE5ETgROBEUEjcSNxE4EjcSOBEUERQSExEUEhMRExEUERQRORE4ETgROBE4EQAFIAABJUoSAAxNAAEmSREADQU="
    - name: Bedroom TV Aspect
      command_on: "JgBgAAABJpMSExITERQSEhEUETkRFBEUETgSNxI3EjcSNxMSETkSNxITETgSNxEUEhMRFBI3EhMSNxITERQROBI3ETkRFBE4EgAFHgABJkkRAAxPAAEmSRIADE4AASVKEQANBQAAAAAAAAAA"
    - name: Bedroom TV Channel Up
      command_on: "JgBYAAABJZQRFBEUERQRFBEUETgRFBITETgTNhI3EjcSOBEUEDkSNxEUETgSExEUERQRFBIUERMROBEUETgSNxI3EjcRORE4EQAFHwABJUoSAAxOAAEmSREADQU="
    - name: Bedroom TV Channel Down
      command_on: "JgBYAAABJZMSExITERQRFBEUETgRFBITETkROBI3EjcROBEUETgRORE4EhMRFBE4ERQRFBEUEhMRFBE4ETgRFBE4ETgROBE5EQAFHwABJUoRAAxPAAEmSREADQU="
    - name: Bedroom TV Volume Up
      command_on: "JgBYAAABJpISExEUERQRFBITEjcSExEUETgSOBE4ETgSNxEUETgSNxE5ETgRFBITEhMSExITEhMRFBETEjgROBI3EjcSNxE5EQAFHwABJkkRAAxPAAElShIADQU="
    - name: Bedroom TV Volume Down
      command_on: "JgBYAAABJpMRFBEUERQSExEUETgRFBEUEjcROBI3EjcROREUEDkROBE4EhMRFBEUEhMRFBE4EhMRFBE4EjcSNxI4ETgSExE4EgAFHwABJUoSAAxNAAEmSREADQU="
    - name: Bedroom TV Volume Mute
      command_on: "JgBYAAABJZMSExITERQRFBEUETgSExEUETgROBI4ETgROBEUEjcSNxE4ETkRFBEUETgRFBE4EhMSExEUEjcROBEUETgRFBE4EgAFHwABJUoRAAxPAAEmSREADQU="
    - name: Bedroom TV 1
      command_on: "JgBYAAABJpMSExITEhMRFBEUETgSExITEjcSNxE4EjcSNxITEjcSOBISERQSFBAUEhMSExITEhMROBI3EjgSNxE4EjcSNxI3EQAFIAABJEoSAAxNAAEmSREADQU="
    - name: Bedroom TV 2
      command_on: "JgBgAAABJpISExITEhMSExITEjcRFBEUETgSNxE5EjcSNxITEjcSNxITERQSExITEjcSExEUEhMROBI3EjcRORITETgSNxI3EgAFHgABJUoRAAxOAAElShIADEwAASZJEgANBQAAAAAAAAAA"
    - name: Bedroom TV 3
      command_on: "JgBgAAABJJQSExEUERQSExITETgRFBITETgROBI3EjcSOBITETgSNxE4EhMRFBEUETgSExITERQRFBE4EjcSNxEUETgSOBI3EgAFHgABJUoSAAxNAAEmSRIADE0AASZJEgANBQAAAAAAAAAA"
    - name: Bedroom TV 4
      command_on: "JgBgAAABJpISExITEhMRFBITETgSExITETgSOBE4EjcROBITEjcSNxI3EjgTEhETEjgRFBITEhISExEUETgROREUEjcROBI3EgAFHgABJkkSAAxNAAElShEADE4AASZJEwANBQAAAAAAAAAA"
    - name: Bedroom TV 5
      command_on: "JgBYAAABJZMSExEUERQSExITEjcSExEUEjcSNxI3ETkSNxITEjcSNxITEhMSNxITETgSExEUERQROBI3EhMROBITETgSOBE4EQAFHwABJkkSAAxMAAEmSRIADQU="
    - name: Bedroom TV 6
      command_on: "JgBYAAABJZMSExEUEhMSExEUETgRFBMSETgSNxI3ETkROBEUEjcROBI3ERQSNxITETgRFBITERQSExI3EhMSNxITETkSNxI3EgAFHgABJUoRAAxOAAEmSRIADQU="
    - name: Bedroom TV 7
      command_on: "JgBgAAABJpISExITEhMSExITEjcSExITEjcSNxI3EjcROBIUETgSNxI3EjcSNxITETgSExEUEhMSExEUERQROBITEjcROBI4EgAFHgABJUoSAAxNAAElShIADE0AASVKEgANBQAAAAAAAAAA"
    - name: Bedroom TV 8
      command_on: "JgBYAAABJZMRFBEUEhMRFBITEjcSExEUETgSNxI4ETgSNxEUETgROBITERQRFBE4EjcSExITERQSNxE4EjgRFBEUEDkSNxI3EgAFHgABJUoRAAxOAAElShIADQU="
    - name: Bedroom TV 9
      command_on: "JgBgAAABJpISExITEhMRFBITEjcRFBITEjcROBI4ETgSNxITEjcSNxE4ERQSExE4EjgRFBEUEBQRFBE5EjcSExEUETgROBI3EgAFHgABJUoSAAxNAAEmSRIADE0AASZJEQANBQAAAAAAAAAA"
    - name: Bedroom TV 0
      command_on: "JgBYAAABJpIRFBEUEhMRFBEUETgRFBITEjcSNxE5EjcROBITETgSNxI3EjcRFBI3EjgSExITERMRFBITEjgRFBETETkROBE4EgAFHgABJkkSAAxNAAEmSREADQU="
    - name: Bedroom TV Dot
      command_on: "JgBYAAABJpISExEUEhMSExITETgSExEUETgSNxE5ETgROBEUEjcSNxEUEhMROBI3EzcQFBIUERMRORE4ERQRFBEUETgROBI3EQAFIAABJUkSAAxOAAElShEADQU="
    - name: Bedroom TV LastChannel
      command_on: "JgBYAAABJZMSExITEhMSExEUEjcRFBITEjcROBE4ETkROBEUETgROBEUEhMROBI3ERQSExE4ERQROBI3ERQRFBE4ETkRFBE4EQAFHwABJUoSAAxNAAElShIADQU="
    - name: Bedroom TV Sleep
      command_on: "JgBYAAABJZQSExEUERQRFBITEjcSExITEjcROBE4EjcSNxITEjgROBEUETgSNxI3EhMRFBI3EhMSNxEUERQRFBI3EjcRFBE4EgAFHwABJUoRAAxNAAEmSRIADQU="

    #IR codes Jalynne TV
    # - name: Jalynne TV
    #   command_on:
    #     'JgBYAAABJ5MTEhM3EzYTEhITEhMSExM2EzYTExE4ERMUERMSEhMSExM2ExISExITEhMTNhM2ExISExM2EzYTNxM2ExITEhI4EgAFmAABJ0oTAAxWAAEoSRMADQU='
    #   command_off:
    #     'JgBYAAABJpQTEhI4EzYTEhITEhMTEhM2FDUTExE4EhITEhMSEhMTEhMSEhITEhMSExISOBE4EhITNxM2EzYTNxI3EhMTEhI4EgAFlwABKEoTAAxWAAEoSRMADQU='
    # - name: Jalynne TV PowerToggle
    #   command_on:
    #     'JgBgAAABJZQRExM3ETgSExEVEBQRFBI3ETgSFBE4ERMSExITEhQQFBI3ETkROBE4EhQRFBAUERQRFBAVERQSExI3EjcROBI4EQAFgwABJUoRAAxDAAElShMADEEAASVKEQANBQAAAAAAAAAA'
    # - name: Jalynne TV Input HDMI1
    #   command_on:
    #     'JgBQAAABKZMTEhI4EzYTERMSExISExM2EzYTEhQ2EhMRExMSFBEUEhETFDUTEhMSEhMTNhMSEzYTNxITETgTNxM2EhIUNRMTFAAFlgABJ0oSAA0FAAAAAAAAAAA='
    # - name: Jalynne TV Input HDMI2
    #   command_on:
    #     'JgBgAAABJpYTEhE3EjgSFBEUExERFBQ1FDUSExQ1FBIRFBMSExIQFBE4ETgSExUREBQROBIUFDQSExEVFDQSNxI4EhQVMxIUEAAFmgABJkoSAAxYAAEoSREADFkAASZLEgANBQAAAAAAAAAA'
    # - name: Jalynne TV Input HDMI Toggle
    #   command_on:
    #     'JgBgAAABJZQRFBE4EjgRFBEUERMSExE5ETgRFBE4ERQRFBEUERQRExITEhMRFBEUETgSExE4EhMSOBE4ETgSOBEUETgRFBE4EgAFggABJUsRAAxCAAElSxEADEIAASdJEwANBQAAAAAAAAAA'
    # - name: Jalynne TV Input TV
    #   command_on:
    #     'JgBgAAABKpEVEhI1FDUVEhMSExISEhQ0FTUVERQ1FBETEhMSExISExI1FTUUNRQ1FRITEhM1FBITERQRFBISEhQ0FDYUEhM2EwAFlwABKEgVAAxWAAEoSBUADFUAAShIFQANBQAAAAAAAAAA'
    # - name: Jalynne TV Input
    #   command_on:
    #     'JgBYAAABJZQRFBE4EjgRFBETEhMRFBE4EjgRFBE4ERQRFBEUERQRExI4ERQROBE4EjgRFBEUERMSExE5ERMSExITETgSOBE4EgAFgQABJ0kRAAxCAAElShEADQU='
    # - name: Jalynne TV Up
    #   command_on:
    #     'JgBYAAABJZQRFBE4ETgSExITERQRFBE4EjgRExI4ERQRFBETEhMSExITETgSExITERQRFBE4EhMROBITEjgROBE4EjgRFBE4EQAFhAABJUoRAAxDAAElShIADQU='
    # - name: Jalynne TV Down
    #   command_on:
    #     'JgBYAAABJZMSExE4EjgRFBEUERMSExI4ETgRFBE4EhMSExEUERQRFBE4ETgSExITERQRFBE4EhMRFBEUETgSOBE4ETgSExI4EQAFgwABJUoSAAxCAAEmShEADQU='
    # - name: Jalynne TV Left
    #   command_on:
    #     'JgBYAAABJZQRExI4ETgSExEUERQRFBE4ETgSExI4ERMSExITEhMRFBEUETgSOBETEjgRFBETEhMSOBEUERMSOBEUETgRORE4EQAFgwABJUsRAAxDAAElShEADQU='
    # - name: Jalynne TV Right
    #   command_on:
    #     'JgBYAAABJZMSExI4ETgRFBEUERQRExI4ETgSExE4EhMSExEUERQRFBE4ERQROBITEjgRExITEhMSExE4EhMSOBETEjgROBI4EQAFgwABJUoSAAxDAAElShEADQU='
    # - name: Jalynne TV OK
    #   command_on:
    #     'JgBYAAABJpMSExE4EjgSExEUERMSExI4ETgSExE4ExISExEUEhMRFBETEhMSExE4EjgRFBEUEhISOBI3EjgRFBETEzcSNxI3EwAFggABJUoTAAxBAAEnSRIADQU='
    # - name: Jalynne TV Menu
    #   command_on:
    #     'JgBYAAABJ5ITEhI3EzcSExITEhITEhM3EjcSExI3ExISExITEhMSExISExITNxISEzcSExITEhITNxI3EhMSNxQREzcSNxI3EwAFgQABJkoSAAxBAAEmSRMADQU='
    # - name: Jalynne TV Exit
    #   command_on:
    #     'JgBgAAABJ5ISExI3EzcSExISExITEhM3EjcSExI3ExISExITEhMSEhQ2EjcTEhI3EzcSExITEhITEhMSEzcSEhQRFDYSNxI3EwAFggABJ0gTAAxBAAEnSRIADEIAASZJEwANBQAAAAAAAAAA'
    # - name: Jalynne TV Home
    #   command_on:
    #     'JgBYAAABJpMSExI3EzcSExISExITEhM3EjcSExI3ExITEhMSExISExI3EhMSExM2EjcTNxMSEjcTEhM2FDYTERQRFBETNxMRFAAFgAABJ0kTAAxAAAEnSBQADQU='
    # - name: Jalynne TV Info
    #   command_on:
    #     'JgBYAAABJpITEhM3ETgSExITEhMSExI3EjcTEhM2ExITEhITEhMSExI3EzcSNxITEjcTEhITEhMSExITEhITNxITEjcSNxM3EgAFggABJ0kSAAxCAAEmSRMADQU='
    # - name: Jalynne TV Channel Up
    #   command_on:
    #     'JgBYAAABJ5ITERQ2EzYUERMSExITEhM2EzYUERQ2ExITERQRFBETEhMSEzYUERM2FBEUERQRExITNhQRFDUUERQ2EzYUNhM2EwAFgAABJ0gUAAw/AAEnSRMADQU='
    # - name: Jalynne TV Channel Down
    #   command_on:
    #     'JgBYAAABJ5EUERQ2EzYTEhMSExITERQ2EzYTEhM2FBEUERQRExITEhM2EzYUERQ2ExITERQRFBETEhMSEzYUERQ2EzYTNhQ2EwAFgQABJkkSAAxBAAEoSBMADQU='
    # - name: Jalynne TV Volume Up
    #   command_on:
    #     'JgBYAAABJpIUERM3EjcTEhMSEhMSEhM3EjcTEhI3ExIUERITEhMSExITEhITNxM2ExITEhMSExISNxI3FBEUERM3EjcSNxQ2EgAFgQABJkkUAAw/AAEmSRMADQU='
    # - name: Jalynne TV Volume Down
    #   command_on:
    #     'JgBYAAABJ5ITEhI3FDYTEhMRExITEhQ2EjcTEhM2ExISExMSEhMTERQ2ExITNhM2ExIUERQREhMSExM2ExITEhM2FDYTNhM2FAAFgAABJ0kTAAxAAAEnSBMADQU='
    # - name: Jalynne TV Volume Mute
    #   command_on:
    #     'JgBYAAABJ5ITEhM2FDUUERQRFBEUERM2FDYTERQ2FBETEhMRFBEUERQRFDUUNhM2FBEUERQRExITNhQRFBETEhM2FDUUNhM2FAAFfwABKEgTAAxAAAEnSBQADQU='
    # - name: Jalynne TV Play
    #   command_on:
    #     'JgBYAAABKJEUERQ1FDYTEhMRFBEUERQ2EzYUERQ1FBEUERQRExITEhMRFBEUERQRFDUUNhM2FBEUNRQ2EzYUNhMRFBEUERQ2EwAFgQABKEgUAAxBAAEnSBQADQU='
    # - name: Jalynne TV Pause
    #   command_on:
    #     'JgBYAAABJZMSExQ2ETgRFBITExISEhI4EjcTEhE4ExISExITExITEhEUETgROBM3EzYUNhM2ERQROBITExIRFBITERMSExM3EgAFgwABJkkTAAxCAAEmSRMADQU='
    # - name: Jalynne TV Stop
    #   command_on:
    #     'JgBYAAABKJETEhM2FDYSExISEhMSExQ2EzYTEhI3ExITEhITExISExI3ExIRFBITEjcTNhM3EhMTERM3EjcTNxMREhMTEhQ2EQAFhAABJkkSAAxDAAEmSRQADQU='
    # - name: Jalynne TV FastForward
    #   command_on:
    #     'JgBYAAABKJEUERM2FDYTEhMRFBEUERQ1FDYTEhM2FBEUERQRExITEhM2ExITNhQ1FDYUNRQ2ExITERQ2ExITEhMRFBEUERQ1FAAFgQABKEgUAAxBAAEnSBQADQU='
    # - name: Jalynne TV Rewind
    #   command_on:
    #     'JgBgAAABJ5ITEhM2FDUUERQRFBEUERM2FDYTEhM2FBETEhMSExEUERQRFDUUNhQ1FDYTNhQ1FBEUNhMSExEUERQRFBEUERQ1FAAFgQABKEgTAAxBAAEoSBMADEEAAShIEwANBQAAAAAAAAAA'
    # - name: Jalynne TV SkipForward
    #   command_on:
    #     'JgBgAAABJ5EUERQ2EzYUERQRExITEhM2FDUUERQ2ExEUERQRFBEUERQ1FDYTNhQ2EzYUNRQ2ExITERQRFBEUERMSFBESExM2EwAFggABJkkUAAxBAAEnSBMADEIAAShIEwANBQAAAAAAAAAA'
    # - name: Jalynne TV SkipBack
    #   command_on:
    #     'JgBgAAABJ5EUERQ2EzYUERQRExITEhM2FDUUERQ2ExEUERQRFBEUERQ1FDYTNhQ2EzYUNRQ2ExITERQRFBEUERMSFBESExM2EwAFggABJkkUAAxBAAEnSBMADEIAAShIEwANBQAAAAAAAAAA'
    # - name: Jalynne TV 1
    #   command_on:
    #     'JgBYAAABKJEUERM2FDYTERQRFBEUERQ1FDYTEhM2FBEUERMSExEUERQRFBEUERMSExITERQRFBEUNRQ2FDUUNhM2FDUUNhM2FAAFgAABJ0gUAAw/AAEoRxQADQU='
    # - name: Jalynne TV 2
    #   command_on:
    #     'JgBYAAABJZMSExI4ETgRFBEUERQRFBE4ETgSExE4EhMSExITERQRFBE4EhMRFBEUERQRFBETEhMSExE4EjgROBI4ETgROBI4EQAFggABJUsRAAxCAAEmSRMADQU='
    # - name: Jalynne TV 3
    #   command_on:
    #     'JgBYAAABJZQRFBE4ETgTEhITERQSExE4EzcRExM3ERQSExISExISExMSEjcTEhMSEhMSExITEhMSNxITEjcTNxI3EjcTNxI3EwAFgQABJkkSAAxBAAEmSRMADQU='
    # - name: Jalynne TV 4
    #   command_on:
    #     'JgBYAAABJpITEhM3EjcSExITEhMSExI3EjcTEhM2ExITEhMSEhMSExI3EzcSEhMSExITEhITEhMSExITEjcSNxM3EjcTNhM3EgAFgQABJkoSAAxBAAElShIADQU='
    # - name: Jalynne TV 5
    #   command_on:
    #     'JgBYAAABJZQRFBE4ETgSExITERQRFBE4ETkRExI4ERQRFBETEhMSExEUERQROBITEhMRFBEUERQROBE4EhMROBI4ETgSOBE4EQAFgwABJUoRAAxCAAElShIADQU='
    # - name: Jalynne TV 6
    #   command_on:
    #     'JgBYAAABJpMRFBE4EjgRFBEUERMSExI4ETgSExE4EhMRFBEUERQRFBE4ERQROBMSERQRFBITERQRExI4EhMROBI3EzcSNxM2EwAFgQABJUoTAAxAAAEmShEADQU='
    # - name: Jalynne TV 7
    #   command_on:
    #     'JgBYAAABJZMSExI4ETgRFBEUERQRFBE4ETgSExI4ERQRExITEhMRFBEUETgRORETEhMSExEUERQROBITERQROBI4ETgROBI4EQAFgwABJUoRAAxBAAEnShEADQU='
    # - name: Jalynne TV 8
    #   command_on:
    #     'JgBYAAABJ5ITEhM2EzYTEhMSExITEhM2EzYUERQ2ExITERQRExITEhM2EzcTNhMSExITEhMSExITERMSExITNhQ2EzYTNxM2EwAFgAABJ0kTAAxAAAEoRxQADQU='
    # - name: Jalynne TV 9
    #   command_on:
    #     'JgBYAAABJZQRFBE4ETgSExITEhMRFBE4EjgRFBE4ERQRFBEUERMSExITERQRFBE4EhMRFBEUERQROBE4EjgRFBE4ETgSOBE4EQAFgwABJUoSAAxCAAEnSBMADQU='
    # - name: Jalynne TV 0
    #   command_on:
    #     'JgBYAAABJZMSExE4EjgRFBEUERMSExI4ETgRFBE4EhMSExEUERQRFBE4ERQRFBE4ERQRFBEUERMSExI4ETgRFBE4EjgROBE5EQAFggABJUsRAAxCAAElShIADQU='
    # - name: Jalynne TV Dot
    #   command_on:
    #     'JgBYAAABJZQRFBE4ETgSExITERQRFBE4EjgRExI4ERQRExITEhMSExE4EhMSExITERQRFBE4ERQRFBE4EjgROBE4FDYRFBE3EgAFgwABJUoSAAxCAAElShEADQU='
    # - name: Jalynne TV LastChannel
    #   command_on:
    #     'JgBQAAABJZMSExI4ETgRFBEUERQRExI4ETgSExE5ERMSExITERQRFBEUERQRExITEjgRExITEhMSOBE4ETgSOBEUETgROBI4EQAFgwABJUoRAA0FAAAAAAAAAAA='
    # - name: Jalynne TV Sleep
    #   command_on:
    #     'JgBYAAABJ5EUERQ2EzYUERMSEhMSEhQ2EzYUERQ1FBEUERMSFBESExM2EzcTERQREzcSExMRExITEhQREzYUNhMSEjcUNRQ2EwAFgQABJ0gUAAxAAAEmSRQADQU='
# RF remote button#1 on:  sgwyAAcTBxMHExQGBxMUBwcTFAYIEwgTCBMUBgcTFAYHExQGBxMHExQGFAYHEwgTFAYUBgfBAAAAAAAA
# RF remote button#1 on:  sg0yAAcTBxMIExQGBxMUBgcTFAYIEwcTCBMUBgcTFAcHExQHCBMIExQGFAYIEwgTFAYUBgfBAAAAAAAA
# RF remote button#1 off: sg0yAAgSCBIIExUGCBMUBwgSFAYIEwgTCBMUBggTFQYIEhQGCBIIEhQGFAYVBhQGCBMHEwjBAAAAAAAA
# RF remote button#1 off: shMyAAgTCBMIExQGCBIVBggTFAYIEggTCBIUBggTFAcHExQGCBMIExQGFAYUBhQHBxMIEwjBAAAAAAAA
# RF remote button#2 on:  sg4yAAcTBxMIExQGBxMUBggTFAYIEwcTCBIVBggTFAYIExQGFAYUBggTCBMIEwgTFQYUBwjCAAAAAAAA
# RF remote button#2 on:  sgoyAAcTCBMIExQGCBMUBggTFAYIEwgTCBIVBggSFQYIEhQGFQYUBggTCBMIEwgTFQYUBgjCAAAAAAAA
# RF remote button#2 off: sgYyAAgTCBMIExUGCBMVBggTFQYIEwgSCBMVBggTFAYIExQGFAYVBggTCBMUBhUGCBMIEwfCAAAAAAAA
# RF remote button#2 off: sg0yAAgTCBIIEhUGCBMUBwcTFAYIEggTCBIUBggTFQYIExUGFAYVBggTCBIVBhQGCBMIEwjCAAAAAAAA
# RF remote button#2 off: sgsyAAgTCBMIExQGBxMVBggSFQYIEwgSCBMVBggTFQYIExQGFQYVBggTCBMVBhQGCBMIEwjBAAAAAAAA
# RF remote button#3 on:  sgoyAAgTCBIIExUGCBIVBggTFQYIEwgTCBMUBggTFAYUBhQGCBMIEggTCBIIEwgTFQYUBgfCAAAAAAAA
# RF remote button#3 on:  sgcyAAgTBxMIExUGCBIVBggTFAYIEwgTCBMUBggSFQYVBhQGCBMIEwgTCBMIEwgTFQYVBgjBAAAAAAAA
# RF remote button#3 off: sg8yAAcTCBMIExUGCBIVBggTFQYIEwgSCBIVBggSFQYVBhUGCBMIEwgTCBMUBhQGCBMIEwjCAAAAAAAA
# RF remote button#3 off: sg0yAAgSCBMIExQGCBMUBggTFQYIEwgSCBIVBggTFQYUBhUGCBMIEwgSCBMUBhUGCBIIEwjCAAAAAAAA
