- platform: template
  switches:
    dining_room_tv:
      value_template: "{{ is_state('input_boolean.dining_room_tv', 'on') }}"
      turn_on:
        - service: switch.turn_on
          data_template:
            entity_id: "{% if is_state('input_boolean.dining_room_tv', 'off') %}switch.dining_room_tv_powertoggle{% else %}switch.null{% endif %}"
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.dining_room_tv
      turn_off:
        - service: switch.turn_on
          data_template:
            entity_id: "{% if is_state('input_boolean.dining_room_tv', 'on') %}switch.dining_room_tv_powertoggle{% else %}switch.null{% endif %}"
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.dining_room_tv            

## Broadlink RM Pro Dining Room s/n RM0 -  ip: 192.168.1.80
- platform: broadlink
  mac: '34:EA:34:C7:CC:BE'
  switches:
    - name: Front Entrance
      command_on:
        '6RRGAN8JFgkWCRYJCRYWCRYJCRYWCRYJCRYJFhYJFgkJFgkWCRYJFhYJFgkWCRYJCRYJFhYJCRYWCRYJFgkJFhYJFgkJFgkAAUg='
      command_off:
        '6RRGAN8JCRYJFhYJCRYWCQkWCRYWCRYJCRYWCRYJCRYWCRYJFgkJFhYJCRYWCQkWCRYWCQkWFgkWCQkWFgkJFgkWFgkWCQkAAUg='
    - name: Front Porch
      command_on:
        '6RRGAN8JCRYJFhYJCRYJFhYJCRYWCQkWFgkJFgkWFgkWCQkWFgkJFgkWCRYWCQkWCRYWCQkWCRYWCRYJFgkWCQkWCRYWCQkAAUg='
      command_off:
        '6RRGAN8JFgkJFgkWCRYWCRYJCRYJFgkWCRYJFgkWCRYWCRYJFgkJFhYJCRYWCRYJCRYJFgkWFgkWCQkWFgkJFhYJCRYJFgkAAUg='
    - name: Dining Room Light
      command_on:
        '6RRGAN8JFgkWCRYJFgkWCQkWCRYWCRYJFgkWCRYJFgkJFhYJCRYWCRYJFgkWCQkWCRYJFgkWFgkJFhYJFgkJFgkWCRYJFgkAAUg='
      command_off:
        '6RRGAN8JCRYJFhYJFgkJFhYJCRYWCQkWFgkWCRYJFgkWCRYJFgkJFgkWCRYJFgkWFgkWCQkWCRYWCQkWFgkJFgkWCRYJFgkAAUg='
    - name: Dining Room Fan
      command_on:
        '6RRGAN8JFgkWCQkWCRYJFgkWCRYJFgkWFgkWCRYJCRYJFgkWFgkWCRYJFgkJFgkWCRYWCRYJCRYJFgkWFgkWCQkWFgkJFgkAAUg='
      command_off:
        '6RRGAN8JCRYJFgkWFgkWCQkWCRYJFhYJCRYJFhYJFgkJFgkWFgkJFgkWCRYWCQkWFgkWCQkWFgkJFgkWFgkWCQkWCRYJFgkAAUg='
    - name: Dining Room Plug
      command_on:
        '6RRGAN8JFgkJFhYJFgkJFhYJFgkJFhYJCRYWCQkWCRYJFgkWFgkWCQkWCRYWCRYJFgkJFgkWFgkWCQkWFgkJFhYJCRYJFgkAAUg='
      command_off:
        '6RRGAN8JFgkJFgkWCRYWCRYJFgkJFhYJCRYJFgkWCRYWCQkWCRYJFhYJFgkJFhYJFgkWCQkWCRYJFgkWFgkJFgkWCRYJFgkAAUg='
    - name: rf_etekcity_1
      command_on:
        'siQyAAcTBxMIExQGCBMUBgcTFAYHEwcTBxMUBgcTFAcHExQHBxMHExQGFAcHEwcTFAcUBgfCAAAAAAAA'
      command_off:
        'shYyAAgTBxMHExQHCBMUBggTFAYHEwgTBxMUBgcTFAYHExQHBxMHExQHFAcUBhQGBxMHEwfBAAAAAAAA'
    - name: rf_etekcity_2
      command_on:
        'sg4yAAcTBxMIExQGBxMUBggTFAYIEwcTCBIVBggTFAYIExQGFAYUBggTCBMIEwgTFQYUBwjCAAAAAAAA'
      command_off:
        'sgYyAAgTCBMIExUGCBMVBggTFQYIEwgSCBMVBggTFAYIExQGFAYVBggTCBMUBhUGCBMIEwfCAAAAAAAA'
    - name: rf_etekcity_3
      command_on:
        'sgoyAAgTCBIIExUGCBIVBggTFQYIEwgTCBMUBggTFAYUBhQGCBMIEggTCBIIEwgTFQYUBgfCAAAAAAAA'
      command_off:
        'sg8yAAcTCBMIExUGCBIVBggTFQYIEwgSCBIVBggSFQYVBhUGCBMIEwgTCBMUBhQGCBMIEwjCAAAAAAAA'
    - name: rf_etekcity_4
      command_on:
        'sgkyAAcTCBMHExUGCBMVBwcTFQYIEwcTCBMVBhUHFQYIExUHCBMIEwgTCBMIEwgTFQYUBgjDAAAAAAAA'      
      command_off:
        'siQyAAgTCBMIExQHBxMUBggTFAYIEwcTBxMVBxQGFQYIExQGBxMIEwgTCBMUBhQHBxMHEwfCAAAAAAAA'      
    - name: rf_etekcity_5
      command_on:
        'shEyAAgTCBMIExQHCBMVBwgTFQcHEwgTFAcVBggTFAYIExQGCBMHEwgTCBMIEwcTFAYVBgjCAAAAAAAA'      
      command_off:
        'sg4yAAcTCBMHExUGCBMUBggTFQcHEwgTFAcUBgcTFAcHExQGCBMHEwgTBxMUBhUHBxMHEwfCAAAAAAAA'
    - name: Butt Kickers    #copy of rf_etekcity_3
      command_on:
        'sgoyAAgTCBIIExUGCBIVBggTFQYIEwgTCBMUBggTFAYUBhQGCBMIEggTCBIIEwgTFQYUBgfCAAAAAAAA'
      command_off:
        'sg8yAAcTCBMIExUGCBIVBggTFQYIEwgSCBIVBggSFQYVBhUGCBMIEwgTCBMUBhQGCBMIEwjCAAAAAAAA'
    #USE SONOFF - name: Deck Fan       #copy of rf_etekcity_1
    #   command_on:
    #     'siQyAAcTBxMIExQGCBMUBgcTFAYHEwcTBxMUBgcTFAcHExQHBxMHExQGFAcHEwcTFAcUBgfCAAAAAAAA'
    #   command_off:
    #     'shYyAAgTBxMHExQHCBMUBggTFAYHEwgTBxMUBgcTFAYHExQHBxMHExQHFAcUBhQGBxMHEwfBAAAAAAAA'
    - name: Ikea Tradfri Gateway       #copy of rf_etekcity_1 ** For now until we need Deck Fan again
      command_on:
        'siQyAAcTBxMIExQGCBMUBgcTFAYHEwcTBxMUBgcTFAcHExQHBxMHExQGFAcHEwcTFAcUBgfCAAAAAAAA'
      command_off:
        'shYyAAgTBxMHExQHCBMUBggTFAYHEwgTBxMUBgcTFAYHExQHBxMHExQHFAcUBhQGBxMHEwfBAAAAAAAA'

    #Don't use - name: Dining Room TV PowerToggle implicitely (use template switch switch.dining_room_tv) as on/off toggle switch turns TV on if all switches being turned off turns off ir_sharp_tv:
    - name: Dining Room TV PowerToggle
      command_on:
        'JgBYAAABKJEUEhMQFDYUERMSExEUERMSEzUUNhQQFDYUNRQ1FDUVNRQQFRAUERQ1FBEUERMSExEUNRQ1FDYUERM2FDUUNRQ2FAAFKgABKEgVAAxTAAEoSBUADQU='
    #Sharp 4k TV IR commands
    - name: Dining Room TV Input TV
      command_on:
        'JgBgAAABKJEVDxMTFDUSExITEhMTEhMQEzcSNxUQEjcSNxM3FDUUNRUQFBASNxUQEjcVNBU1FA0VOBE4ERMSNxUQEhMUEBM3FAAFJQABJkoSAAxPAAEpRxUADEwAASVKEgANBQAAAAAAAAAA'
    - name: Dining Room TV Input HDMI1
      command_on:
        'JgBgAAABJ5MTERQRFDUUERMRFBITEhISFDUUNRQRFDUUNRQ1FDYUNRQRExEUNRQ1FDUUNRU1FBEUNRQ1FBETEhMRFBEUERM2EwAFJwABJ0gUAAxNAAEoSBQADE0AAShIEwANBQAAAAAAAAAA'
    - name: Dining Room TV Input FireTV
      command_on:
        'JgBgAAABJ5MTERQRFDUUERMRFBITEhISFDUUNRQRFDUUNRQ1FDYUNRQRExEUNRQ1FDUUNRU1FBEUNRQ1FBETEhMRFBEUERM2EwAFJwABJ0gUAAxNAAEoSBQADE0AAShIEwANBQAAAAAAAAAA'
    - name: Dining Room TV Input Roku
      command_on:
        'JgBgAAABJ5MTERQRFDUUERMRFBITEhISFDUUNRQRFDUUNRQ1FDYUNRQRExEUNRQ1FDUUNRU1FBEUNRQ1FBETEhMRFBEUERM2EwAFJwABJ0gUAAxNAAEoSBQADE0AAShIEwANBQAAAAAAAAAA'
    - name: Dining Room TV Input HDMI2
      command_on:
        'JgBgAAABKZITERQRFDUUERMSExEUERQREzYTNhQREzYUNRQ1FDUUNRQ2ExITNhQ1FDUUNRQ1FBETEhM2FBEUERMRFBEUERQ1FAAFJQABKEgUAAxOAAEnSBMADE4AASdJEwANBQAAAAAAAAAA'
    - name: Dining Room TV Input Chromecast
      command_on:
        'JgBgAAABKZITERQRFDUUERMSExEUERQREzYTNhQREzYUNRQ1FDUUNRQ2ExITNhQ1FDUUNRQ1FBETEhM2FBEUERMRFBEUERQ1FAAFJQABKEgUAAxOAAEnSBMADE4AASdJEwANBQAAAAAAAAAA'
    - name: Dining Room TV Input HDMI3
      command_on:
        'JgBwAAABJpMUERQREzYTERQRFBISEhMSEzYTNhMSEzYUNRM2EzcSNxITEjcSNhQ1FDUUNhM2ExITNhMSExITERQRFBETERQ1FAAFJgABKEgTAAxOAAEnSRMADE4AASdIFAAMTgABJ0gTAAxOAAEnSRMADQUAAAAAAAAAAA=='
    - name: Dining Room TV Input HDMI4
      command_on:
        'JgBoAAABKJIUERMRFDUUEhMSEhMSEhMSEzYUNRQREzYTNhM2EzcTNhM2EzYTNhM2EzYTNxM2ExEUERQRExEUERQRExEUERQ1FAAFJgABKEgTAAxOAAEnSRIADE8AASdIFAAMTQABJ0gUAA0F'
    - name: Dining Room TV Up
      command_on:
        'JgBYAAABJ5MTEhITEjcSExMSEhMTERMSEzcTNhITEzcSNxM3EzYTNxMSEjcTNxMSEzYTEhI3ExISOBMSEhISOBITEjcTEhM3EgAFLgABKEkTAAxeAAEnShIADQU='
    - name: Dining Room TV Down
      command_on:
        'JgBYAAABJ5QSEhITEjgSEhMSExISExISEzcTNxISEzcSNxM3EzYTNxM3EjcTNxMREzcTEhM2ExISExMSEhISOBMSEjcTEhI4EgAFLQABJ0oTAAxdAAEoShMADQU='
    - name: Dining Room TV Left
      command_on:
        'JgBYAAABJpQSExMSEzYSExMSEhMSEhMSEzcSNxMSEjgSNxI4EjcSOBITExETEhI4EzYTEhI4ExEXMxM3EzYSExITEzYTEhM3EgAFMAABJ0oTAAxfAAEnSxMADQU='
    - name: Dining Room TV Right
      command_on:
        'JgBYAAABKJMTEhMREjgTEhMREhMSExITEjcTNxMSEzYTNxM2EzcTNhM3ExITERM3EzYTEhM3ExETEhI4EzYTEhITEjcTEhM3EwAFLgABJ0oSAAxgAAEoSRMADQU='
    - name: Dining Room TV OK
      command_on:
        'JgBYAAABJpQTEhITEjcTEhMSEhMSEhITEjgSNxITEjgSNxM3EjcSOBMREzcSExI3EjgTEhI3ExISNxMSEjgSExISEjgSExI3EgAFMAABJ0oTAAxgAAEmSxIADQU='
    - name: Dining Room TV Back
      command_on:
        'JgBYAAABKJMTEhISEzcSExMRExISExITEjcTNxITEjcTNxI3EjgSNxMSExISNxMSEhMSExISEhMSOBI3ExISNxI4EjcTNxI4EgAFLQABJ0oTAAxcAAEoSRIADQU='
    - name: Dining Room TV Exit
      command_on:
        'JgBYAAABJ5QUERMSEjcSExITEhISExITEjcTNxITEjcSOBM2EzcSOBI3EhMTNhQ2ExISExM2EhMSExM2EhMTEhM2EzcSExI3EgAFLwABJ0oTAAxdAAEnSxIADQU='
    - name: Dining Room TV Channel Up
      command_on:
        'JgBYAAABKJMTEhMRFDYTEhMRFRATEhMSFDUUNhMSEzYTNxQ1EzcUNRMSExITEhMRFBETEhMSExEUNhM3EzYTNxM2EzcTNhM3EwAFMQABKEkUAAxfAAEoSRUADQU='
    - name: Dining Room TV Channel Down
      command_on:
        'JgBYAAABKZETEhMSEzYUERMSFBETERUQEzcUNRMSEzcTNhM3EzYTNxQ1ExITEhMRFBETEhMSExIUEBQ2EzYUNhM2FTUTNxM2EwAFLwABKEkUAAxeAAEoSRQADQU='
    - name: Dining Room TV Volume Up
      command_on:
        'JgBYAAABKJMTERMSEzcTERQRFRATEhMRFTUVNBUQEzcTNhU1FTQVNRMSFTQVEBQRExITERMSExITNhMSEzcTNhM3EzYTNxM2EwAFLgABKEgUAAxcAAEpSBQADQU='
    - name: Dining Room TV Volume Down
      command_on:
        'JgBYAAABKJMTEhMRFDYTEhMRFBETEhMSEzYTNxMSEzYTNxM2EzcTNhQ2EzYTEhMSExITERQRExITEhMRFDYTNxM2FTUTNhM3EwAFLAABKEkUAAxcAAEoSRUADQU='
    - name: Dining Room TV Mute
      command_on:
        'JgBYAAABKpEVEBUPFjQVEBUPFg8VEBUQFTQWNBUQFTQVNRU0FTUVNBU1FRAVDxY0FRAVDxYPFRAVEBU0FjQVEBU0FTUVNBY0FQAFLgABKkcWAAxdAAEqRxUADQU='
    - name: Dining Room TV Play
      command_on:
        'JgBYAAABJ5QTEhMTETcSExITEhQQExITEjgTNhQREjgSNxM3EjcTNxMREjgSExMSEhISExM3ExESOBMSEzYTNxM2EzcSExI3EgAFMAABJ0oTAAxeAAEoShIADQU='
    - name: Dining Room TV Stop
      command_on:
        'JgBYAAABJ5QSExEUETgRFBITERMRFBITEjcSNxIUETgTNxE4ETgSOBEUETkUNBM3EhMSExI4ERQQOREUERURExE3EzgRExI3EgAFMAABKEkTAAxfAAEnShIADQU='
    - name: Dining Room TV Pause
      command_on:
        'JgBYAAABKJMSExMREjgSExISFBESExMSEjcUNhMSEjcSOBM2EzcTNhM3ExISExETEhMSFBE3ExMQFBI3EzcSNxM3EjgSEhI4EwAFLQABJ0oTAAxcAAEmSxIADQU='
    - name: Dining Room TV Rewind
      command_on:
        'JgBYAAABJpQSExMSEzYSFBETEhMRExITEjcTNxITEzYTNxM2EjgSNxI4EzcSNxM3EhITEhI4EhITEhITExMRExI3EzcTERM3EgAFLwABJksSAAxeAAEmSxMADQU='
    - name: Dining Room TV FastForward
      command_on:
        'JgBYAAABJpQSExITEzYTEhITExISEhMSEjgSNxITEjgSNxI4EjcTNxI3EjgTEhI3EzcSEhI4EhMTEhISEzcSExMREzcSExI3EgAFMQABJ0oSAAxgAAEoSRIADQU='
    - name: Dining Room TV Input
      command_on:
        'JgBYAAABKJMTEhISEjgSExISExISExMSEjcSOBMSEjcSOBI3EjgSNxM3EjgSEhI4EhMSEhITExISExITEjcSExI3EjgSOBI3EgAFMAABJksTAAxeAAEnShIADQU='
    - name: Dining Room TV Settings
      command_on:
        'JgBYAAABJ5MSExQREjcTEhITEhISExIUEjcSNxITEjcSOBI3EzcSOBI3EjgSExISEhMSFBI2EhMSExMSEjcSOBI3EjgTEhI3EgAFMAABKEkSAAxgAAEmSxMADQU='
    - name: Dining Room TV Home
      command_on:
        'JgBYAAABJ5QTEhISEjgSExISEhMSExITEzYSOBITEjcSOBI3EzcTNhITEjgSEhI4EhMSExI3ExISNxITEjgSEhI4EjgSEhI4EgAFMgABJksSAAxhAAEnShMADQU='
    - name: Dining Room TV Apps
      command_on:
        'JgBYAAABJ5MTEhITEjgTERITEhMSExISEjgSOBISEjgTNhM3EjgSNxI4EzYSOBM2ExITEhMSExISEhMSEhMSExI3EzcTNhI4EwAFLwABJ0oTAAxfAAEnShIADQU='
    - name: Dining Room TV Netflix
      command_on:
        'JgBYAAABJpQSExMTETcTEhMSExISExMREjgTNhMSEjgTNhM3EjcTNxMSExISNxI4ExITERI4EhMTNhI4EhMTERI4EjcTEhM3EgAFMAABJ0sSAAxgAAEoShMADQU='
    - name: Dining Room TV YouTube
      command_on:
        'JgBYAAABJ5MTEhITEjgSEhITExITEhEUETgTNhMSEzcSNxI4EjcTNxM2ExITEhI4EhMRExI4EhITEhM3EzYTEhI4EjcTEhI3EgAFMAABJ0oTAAxdAAEoSRIADQU='
    - name: Dining Room TV 1
      command_on:
        'JgBYAAABKJMTEhMREzcTEhMRFBETEhMSEzYTNxMSEzYTNxM2EzcTNhM3ExITERMSEzcTERQRExITEhM2EzcTNhMSEzcTNhM3EwAFLwABKEkTAAxfAAEoSRQADQU='
    - name: Dining Room TV 2
      command_on:
        'JgBYAAABKJMTEhMRFDYTEhMRFBETEhMSEzYTNxMSEzYTNxM2EzcTNhMSEzcTERMSEzcTERQRExITNhQREzcTNhMSEzcTNhM3EwAFMAABKEkUAAxfAAEoSRMADQU='
    - name: Dining Room TV 3
      command_on:
        'JgBYAAABKJMTEhMSEzYTEhMSExEUERMSEzYUNhMSEzYTNxM2FDYTNhQ2EzcTERMSEzcTERQRExITEhMRFDYTNhQREzcTNhQ2EwAFLAABKEkUAAxcAAEoSRMADQU='
    - name: Dining Room TV 4
      command_on:
        'JgBYAAABKJMTEhMRFTUTEhUPFBEVEBMSEzYTNxMRFjQTNxU0EzcTNhMSExITNhMSEzYWDxMSExIVNBM3FQ8UNhMSEzYTNxM2FAAFLwABJ0oTAAxeAAEoSRMADQU='
    - name: Dining Room TV 5
      command_on:
        'JgBYAAABJ5MTEhMSEzYTEhMSExEUERMSEzcTNhYPEzYUNhM2FDYTNhQ2ExITNhQREzcTERQRExITEhM2ExITNxMRFDYTNhQ2EwAFLQABKEkTAAxcAAEoSRMADQU='
    - name: Dining Room TV 6
      command_on:
        'JgBYAAABKJMTERMSEzcTERQRExITEhMRFDYTNhQREzcTNhM3EzYUNhMSEzYTNxMRFDYTEhMSExEUNhMSExEUNhMSEzYTNxM2EwAFLgABKEkTAAxdAAEoSRMADQU='
    - name: Dining Room TV 7
      command_on:
        'JgBYAAABKJITEhMSEzYUERMSExITERQREzcTNhMSEzcTNhM3EzUUNxM2EzcTNhQREzcTERQRExITEhMSExETNxMSEzYTNxM2FAAFMgABKEkUAAxhAAEoSRQADQU='
    - name: Dining Room TV 8
      command_on:
        'JgBYAAABKJIVEBMSEzYUERMSExIUERMRFDYTNhQREzcTNhM3EzYTNxMSExEUERM3EzYTEhMSExEUNhM3EzYTEhUQEzYTNxM2EwAFLQABKkcTAAxcAAEoSRMADQU='
    - name: Dining Room TV 9
      command_on:
        'JgBYAAABKJMTERUQEzcTERQRExITEhMSEzYTNxMRFDYTNxM2EzcTNhM3ExEUERM3EzYUERMSExITERQ2EzYUERQREzcTNhM3EwAFLgABKEkTAAxeAAEoSRQADQU='
    - name: Dining Room TV 0
      command_on:
        'JgBYAAABKJITEhMSEzYTEhMSExITERQREzcTNhMSEzcTNhM3EzYTNxMRFBETEhMSEzYTEhMSExITNhM3EzYTNxMRFDYTNxM2EwAFMgABKEkTAAxhAAEoSRMADQU='
    - name: Dining Room TV Dash
      command_on:
        'JgBYAAABKJIUERYPEzYUERMSExITERQREzcTNhMSEzYUNhM2FDYTNxMREzcTEhM2ExITEhMRFBETNxMRFDYTEhM2EzcTNhM3EwAFLgABKEkTAAxdAAEoSRMADQU='
    - name: Dining Room TV Red
      command_on:
        'JgBYAAABKZETEhUQEzYTEhMSExETEhMSEzYTNxMSFTQTNxU0EzcVNBUQEzcTERMSEzcTERQ2ExITNhUQEzYUNhMSEzYVEBM3EwAFLAABKkcVAAxZAAEoSRUADQU='
    - name: Dining Room TV Green
      command_on:
        'JgBYAAABKJIUERUQFTQVEBMSFRATERQRFTUTNhMSEzcVNBM3EzYTNxM2FTUVEBMRFDYTEhM2ExITEhMSFTQTNxUPFjQTEhM2FAAFLQABKEkUAAxdAAEqRxUADQU='
    - name: Dining Room TV Yellow
      command_on:
        'JgBYAAABKpEVEBUQEzYTEhYPExIVDxYPFTUTNhUQFTUVNBU1FTQTNxYOFRAWNBUPFjQVEBU0ExITNxU0FRAVNBQREzcTERY0EwAFLwABKEkWAAxcAAEoSRMADQU='
    - name: Dining Room TV Blue
      command_on:
        'JgBYAAABKJIUERMSEzcTERQRExITEhMRFDYTNxMREzcTNhQ2EzYUNhM3ExEUNhMSEzYTEhM2FBETEhM3ExEUNhMSEzYTEhM3EwAFMQABJ0oTAAxgAAEoShMADQU='
    - name: Dining Room TV Sleep
      command_on:
        'JgBYAAABJ5MSFBEUETgTERITEhQRExISEjgTNhQREjgTNhM3EjcTNxM2EzcTExE3EzcTEhMREhMTEhMTETcSFBETEjcTNxM2EgAFMQABJksRAAxgAAEnShMADQU='
    - name: Dining Room TV LiveTV
      command_on:
        'JgBYAAABIZkQFBEVDzkQFhEUEBQPFw8UEjkPORAVETkPOhA5ETkROBE5EBYPORE7DjoQFBAWDhYQFRA5EhUOFg8UETgSOBE4EQAFLwABJkwQAAxeAAEmSxEADQU='

    # #IR codes Kale TV 
    # - name: Kale TV PowerToggle
    #   command_on:
    #     'JgBYAAABJpQSExITEzcSExITEhMTExEUETgTNxITEjgSOBI3EjgSOBITEhMSExM3EhMTEhIUERMSOBM3EjgRFBI3FDYSOBM3EgAFGwABJkoSAAxTAAEmShIADQU='      
    # - name: Kale TV Input
    #   command_on:
    #     'JgBQAAABJpMSExITEjgSExITEhMSFBEVETcSOBMSETkSOBI4EjcSOBI4EjgRFBE4EhQRFBEUEhMSExITEjgSExM3ETgTNxI4EgAFGwABJksRAA0FAAAAAAAAAAA='
    # - name: Kale TV Up
    #   command_on:
    #     'JgBYAAABJpQRFBITEjgSExIUERQSEhITEjgSOBEUEjcRORM3EjgSNxIUERQRFBITExISExM3EhMSOBE4EzcSOBI4ETgSExI4EgAFHQABJkoTAAxTAAEmShMADQU='      
    # - name: Kale TV Down
    #   command_on:
    #     'JgBYAAABJpQTEhMSEzcSExITExISExIUETgSOBIUETgROBI4EjgSOBI3EhQSExEUEhMTEhI4EhMRFRE4ETgSOBM3EjgSExE4EgAFHAABJ0kSAAxSAAEmSxEADQU='      
    # - name: Kale TV Left
    #   command_on:
    #     'JgBYAAABJpQSExEUEzcSExITExITEhITEjkROBITEjgSNxM4ETgSOBE4EzcTNxIUEhISExMSEhMSFBEUERQROBI4EzcTNxI3EwAFHAABJkoSAAxUAAEmShMADQU='      
    # - name: Kale TV Right
    #   command_on:
    #     'JgBYAAABJ5MSExITEjcSFBEUEhQQFBITEzgSNhIUETgUNhI4EzcROBMSEzcTNxIUERMTEhITEhMSOBITEhMSOBI4EjgROBI4EgAFGwABJksTAAxRAAEmShIADQU='      
    # - name: Kale TV Enter
    #   command_on:
    #     'JgBYAAABJpQRFBEUEjcTExEUERQRFRETEjgSNxIUETgSOBI4ETgSOBITEhMSOBITEhMSFBE4EhMTNxI4ExISOBI3EzcSExI4EgAFHQABJkoSAAxUAAElSxEADQU='
    # - name: Kale TV Volume Up
    #   command_on:
    #     'JgBYAAABKJISExITFDYSExMSEhQRFBITEjcSOBITEjgTNxI4EjcSORISEjgTExISEhMSExITFRARORMSEjgROhE4ETkSNxI4EgAFGwABJksSAAxSAAEmSxEADQU='      
    # - name: Kale TV Volume Down
    #   command_on:
    #     'JgBYAAABJpQSExITEzcSExMSEhMSFBEUETgTNxITEjgSOBI4ETgSOBI4EjgSExITEhMSExMSEhMSExMSEjgTNxM3ETgSOBI4EgAFHQABJkoSAAxUAAEmShMADQU=' 
    # - name: Kale TV Volume Mute
    #   command_on:
    #     'JgBYAAABJpMTExEUETkRFBETEhQRFBEVETgROREUETgTNxM3ETkSNxI5EhISFBI3ExMRFBETEhMSExI4EzcSExM4ETgSOBI3EgAFHQABJkoTAAxUAAElShIADQU='
        
    # #IR codes Kale dining_room Speakers
    # kale_speakers_powertoggle:
    #   command_on:
    #     'JgBYAAABKJUTEhMSEhMSFBI4ExISExITEjgSORI4ExISExI4EjgSOBI5ERQSExMSExMSExITEhQRExM3EjkSOBI4EjgRORI4EgAFNQABKEsSAAxMAAEpShIADQU='      
    # kale_speakers_mute:
    #   command_on:
    #     'JgBYAAABJ5YTEhQREhMSFBI4ExITEhITEzcSORM3EhMTEhM3EzcTNxMTEhMSExITEhQSExITEhMSOBM3EjgSORI4EjgSOBI4EwAFMwABKEsTAAxMAAEoShMADQU='      
    # kale_speakers_volume_down:
    #   command_on:
    #     'JgBYAAABJ5UTEhMTEhMSExI4ExISExMTETkSOBI4EhMTEhI4EzcTNxIUERQTNxM3EhMSExMSEhQSOBI4EhMSExI4EjgSOBI4EwAFMwABKEsSAAxLAAEpShIADQU='    
    # kale_speakers_volume_up:
    #   command_on:
    #     'JgBYAAABKJQTExITEhMTEhI4EhMUEhITEjgTNxI4ExISExI4EzgSOBM3ExISExM3EhMSFBMSExMRExI4EjgTExI4EjgTNxM3EwAFMgABKUoTAAxJAAEoShIADQU='      
    # kale_speakers_line1:
    #   command_on:
    #     'JgBYAAABKJUTEhITExMSExI4EhMSExIUETkSOBM3ERQSFBE4EjgTNxMUETgSExM3ExISFRETEhMSOBMTETgSFBI4EjgSOBI4EwAFMwABKUoSAAxMAAEpShIADQU='      
    # kale_speakers_line2:
    #   command_on:
    #     'JgBYAAABKpMSExMSEhMSExI5EhMTEhITEzcSOBM3ExMSExI4EjgTNxM3ExMSNxMSEjgTExMSEhMSFBA5ExMSOBITEzcTNxM3EwAFMgABKEsTAAxIAAEoSxIADQU='      
    # kale_speakers_optical:
    #   command_on:
    #     'JgBYAAABKZQSExITEhMSFBI4EhQRExITEzcSORE5EhQRExI4EjgSOBI4EhQSOBI4ExISFBETEhQTEhM3EhQSExE5EjgRORM3EgAFNAABKEwRAAxMAAEoSxMADQU='      
    # kale_speakers_coax:
    #   command_on:
    #     'JgBYAAABKJUSExMTEhMSExI4ExMRExIUEjgTNxM3ExISExI4EjkSOBMSEzcTNxITEzcTExITExITNxMSEhQSOBITEzcTNxM3EwAFMwABKEsTAAxLAAEqSRMADQU='      
    # kale_speakers_bluetooth:
    #   command_on:
    #     'JgBYAAABKJQSFBITEhQRFBE4ExMTEhITEjgSOBM3ExMSFBE4EzcTNxITEzcSORI4ExITEhITExMSOBITExMRExI4EjgSORI4EgAFNAABKEsTAAxLAAEpShMADQU='      
    # kale_speakers_playpause:
    #   command_on:
    #     'JgBYAAABKJQSFBMSEhMTEhM3EhQSExITEjgTNxM3ExQQFBI4EjgSOBMSExMSOBQREjgTEhIUEhMTNxM3ExISOBITEjgSORI4EgAFNAABKEsTAAxLAAEoSxMADQU='      
    # kale_speakers_skip_back:
    #   command_on:
    #     'JgBYAAABKJUTEhMTExISExI4ExITExMSEjgSOBI4ExMRFBI4EzcSOBMSEjgSOBMSFBMRExITEhMSOBMTEhMSOBI4EjgTNxM3EgAFNQABKEsSAAxMAAEoSxIADQU='      
    # kale_speakers_skip_forward:
    #   command_on:
    #     'JgBYAAABKJURFBMTExISExM3EhMSFRETEjgSOBM3ExIRFRI4EjgTOBETExISFBI4EhMTEhIUERQROBM4EjgSFBE4FDYSOBM3EgAFNAABKUoSAAxNAAEpShMADQU='      
        

    # #Old 32"Dynex TV    
    # - name: Kale TV powertoggle:
    #   command_on:
    #     'JgBgAAABKJMUERQ3EzcTExMSExMSExM4EjgTEhQ3ExITExQRExMSExM4EzcUNhQ3ExITExMSFBISExQSEhMTExI4EzcTOBM3FAAFdAABKEkTAAxOAAEnShMADE4AAShJEwANBQAAAAAAAAAA'      
    # - name: Kale TV direction_up:
    #   command_on:
    #     'JgBQAAABJZQRFBE4ETgSExITERQRFBE4EjgRExI4ERQRFBETEhMSExE4EjgRFBEUERMSExI4ERQRExITEjgROBE4EjgRFBE4EQAFgwABJkoRAA0FAAAAAAAAAAA='      
    # - name: Kale TV direction_down:
    #   command_on:
    #     'JgBQAAABJZQRFBE4ETgSExITERQRFBE4EjgRExI4ERQRFBETEhMSExE4EjgRFBEUERMSExI4ERQRExITEjgROBE4EjgRFBE4EQAFgwABJkoRAA0FAAAAAAAAAAA='      
    # - name: Kale TV direction_left:
    #   command_on:
    #     'JgBQAAABJZQTEhE4EzcRExQRExITEhM2EjgRFBM2ERQTEhETFBEUERITEzYUNhEUEzYTEhMSExITNhMSExIROBMSETgSOBE4EQAFhAABJUoRAA0FAAAAAAAAAAA='      
    # - name: Kale TV direction_right:
    #   command_on:
    #     'JgBYAAABJ5ITEhM2EjgTEhMREhMUERE4FDYRFBM2ExITEhEUERQTERQ2ExIROBMSEzYSExEUExIRFBE4ERQROBITETgSOBE4EgAFgwABJUoRAAxDAAElShIADQU='      