- alias: Wayne is in Kitchen
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_wayne_kitchen_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_wayne_bedroom_gh_rssi") ) > ( states("sensor.presence_wayne_kitchen_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_wayne_bedroom_gh_rssi") ) > ( states("sensor.presence_wayne_kitchen_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_wayne_kitchen
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_wayne_bedroom
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_wayne_room_location
        option: Kitchen
- alias: Wayne is in Bedroom
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_wayne_bedroom_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_wayne_kitchen_gh_rssi") ) > ( states("sensor.presence_wayne_bedroom_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_wayne_kitchen_gh_rssi") ) > ( states("sensor.presence_wayne_bedroom_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_wayne_bedroom
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_wayne_kitchen
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_wayne_room_location
        option: Bedroom        
        
- alias: Jenn is in Kitchen
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_jenn_kitchen_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_jenn_bedroom_gh_rssi") ) > ( states("sensor.presence_jenn_kitchen_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_jenn_bedroom_gh_rssi") ) > ( states("sensor.presence_jenn_kitchen_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_jenn_kitchen
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_jenn_bedroom
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_jenn_room_location
        option: Kitchen
- alias: Jenn is in Bedroom
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_jenn_bedroom_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_jenn_kitchen_gh_rssi") ) > ( states("sensor.presence_jenn_bedroom_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_jenn_kitchen_gh_rssi") ) > ( states("sensor.presence_jenn_bedroom_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_jenn_bedroom
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_jenn_kitchen
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_jenn_room_location
        option: Bedroom  
        
- alias: Kale is in Kitchen
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_kale_kitchen_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_kale_bedroom_gh_rssi") ) > ( states("sensor.presence_kale_kitchen_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_kale_bedroom_gh_rssi") ) > ( states("sensor.presence_kale_kitchen_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_kale_kitchen
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_kale_bedroom
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_kale_room_location
        option: Kitchen
- alias: Kale is in Bedroom
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_kale_bedroom_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_kale_kitchen_gh_rssi") ) > ( states("sensor.presence_kale_bedroom_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_kale_kitchen_gh_rssi") ) > ( states("sensor.presence_kale_bedroom_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_kale_bedroom
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_kale_kitchen
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_kale_room_location
        option: Bedroom                
        
- alias: Jalynne is in Kitchen
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_jalynne_kitchen_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_jalynne_bedroom_gh_rssi") ) > ( states("sensor.presence_jalynne_kitchen_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_jalynne_bedroom_gh_rssi") ) > ( states("sensor.presence_jalynne_kitchen_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_jalynne_kitchen
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_jalynne_bedroom
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_jalynne_room_location
        option: Kitchen
- alias: Jalynne is in Bedroom
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.presence_jalynne_bedroom_gh_rssi
  condition:
    - condition: template
      value_template: '{{ ( states("sensor.presence_jalynne_kitchen_gh_rssi") ) > ( states("sensor.presence_jalynne_bedroom_gh_rssi") )  }}'
  action:
    - delay: '00:00:05'
    - condition: template
      value_template: '{{ ( states("sensor.presence_jalynne_kitchen_gh_rssi") ) > ( states("sensor.presence_jalynne_bedroom_gh_rssi") )  }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence_jalynne_bedroom
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence_jalynne_kitchen
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_jalynne_room_location
        option: Bedroom                