- alias: 'Person Home Lights'
  initial_state: 'on'
  trigger: 
    - platform: state
      entity_id: input_select.presence_wayne_status
      from: 'Away'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.presence_jenn_status
      from: 'Away'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.presence_kale_status
      from: 'Away'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.presence_jalynne_status
      from: 'Away'
      to: 'Just Arrived'
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: '{{ state_attr("sun.sun", "elevation") < 2.5 }}'
          - condition: and
            conditions:
              - condition: template
                value_template: '{{ state_attr("sun.sun", "elevation") < 5.5 }}'
              - condition: template
                value_template: '{{ states("sensor.dark_sky_cloud_coverage") | float > 75 }}'
          - condition: and
            conditions:
              - condition: template
                value_template: '{{ state_attr("sun.sun", "elevation") < 8.5 }}'
              - condition: template
                value_template: '{{ states("sensor.dark_sky_cloud_coverage") | float > 95 }}'
      - condition: or
        conditions:
          - condition: template
            value_template: '{{ trigger.entity_id == "input_select.presence_wayne_status" and is_state("input_boolean.home_arrival_automations_wayne", "on") }}'
          - condition: template
            value_template: '{{ trigger.entity_id == "input_select.presence_jenn_status" and is_state("input_boolean.home_arrival_automations_jenn", "on") }}'
          - condition: template
            value_template: '{{ trigger.entity_id == "input_select.presence_kale_status" and is_state("input_boolean.home_arrival_automations_kale", "on") }}'
          - condition: template
            value_template: '{{ trigger.entity_id == "input_select.presence_jalynne_status" and is_state("input_boolean.home_arrival_automations_jalynne", "on") }}'
  action:
    - service: script.lights_arrival
    - condition: template   #only continue on for Jenn or Wayne          
      value_template: '{{ trigger.entity_id == "input_select.presence_wayne_status" or trigger.entity_id == "input_select.presence_jenn_status" }}'
    - service: script.lights_arrival_kitchen_island

- alias: 'Person Home Lights Porch Off'
  initial_state: 'on'
  trigger: 
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.arrival_lights_porch_timeout
  action:
    - service: light.turn_off
      entity_id: light.entrance_light_porch
- alias: 'Person Home Lights Entrance Off'
  initial_state: 'on'
  trigger: 
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.arrival_lights_entrance_timeout
  action:
    - service: light.turn_off
      entity_id: light.entrance_light
    
- alias: 'Away Home Timeout Kale'
  initial_state: 'on'
  trigger: 
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.away_home_timeout_kale
  action:
    - service: input_boolean.turn_on             #re-enable Arrival lights
      entity_id: input_boolean.home_arrival_automations_kale
      
- alias: 'Away Home Timeout Jalynne'
  initial_state: 'on'
  trigger: 
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.away_home_timeout_jalynne
  action:
    - service: input_boolean.turn_on             #re-enable Arrival lights
      entity_id: input_boolean.home_arrival_automations_jalynne