- platform: template
  sensors:
    location_away_wayne:
      friendly_name: "Wayne's Away Location"
      value_template: >-
        {% if is_state("device_tracker.phone_wayne_gps", "Wayne Work") %}
          Work
        {% elif states("device_tracker.phone_wayne_gps") != 'home' and states("device_tracker.phone_wayne_gps") != 'not_home' %}
          {{ states("device_tracker.phone_wayne_gps") }}
        {% endif %}  
    presence_wayne_status:
      friendly_name: 'Wayne'
      value_template: '{{ states("input_select.presence_wayne_status") }}'
    # presence_wayne_status_room:
    #   value_template: '{{ states("input_select.presence_wayne_room_location") }}'
    #   friendly_name: 'Wayne Room Location'
    # presence_wayne_kitchen_gh_rssi:
    #   value_template: >-
    #     {% if is_state("device_tracker.phone_wayne_bt_kitchen", "home") %}
    #       {{ state_attr("device_tracker.phone_wayne_bt_kitchen", "rssi") }}
    #     {% else %}
    #       -99
    #     {% endif %}
    # presence_wayne_bedroom_gh_rssi:
    #   value_template: >-
    #     {% if is_state("device_tracker.phone_wayne_bt_bedroom", "home") %}
    #       {{ state_attr("device_tracker.phone_wayne_bt_bedroom", "rssi") }}
    #     {% else %}
    #       -99
    #     {% endif %}

    location_away_jenn:
      friendly_name: "Jenn's Away Location"
      value_template: >-
        {% if is_state("device_tracker.phone_jenn_gps", "Jenn Work") %}
          Work
        {% elif states("device_tracker.phone_jenn_gps") != 'home' and states("device_tracker.phone_jenn_gps") != 'not_home' %}
          {{ states("device_tracker.phone_jenn_gps") }}
        {% endif %}  
    presence_jenn_status:
      friendly_name: 'Jenn'
      value_template: '{{ states("input_select.presence_jenn_status") }}'

    location_away_kale:
      friendly_name: "Kale's Away Location"
      value_template: >-
        {% if states("device_tracker.phone_kale_gps") != 'home' and states("device_tracker.phone_kale_gps") != 'not_home' %}
          {{ states("device_tracker.phone_kale_gps") }}
        {% endif %}  
    presence_kale_status:
      friendly_name: 'Kale'
      value_template: '{{ states("input_select.presence_kale_status") }}'

    location_away_jalynne:
      friendly_name: "Jalynne's Away Location"
      value_template: >-
        {% if states("device_tracker.phone_jalynne_gps") != 'home' and states("device_tracker.phone_jalynne_gps") != 'not_home' %}
          {{ states("device_tracker.phone_jalynne_gps") }}
        {% endif %}  
    presence_jalynne_status:
      friendly_name: 'Jalynne'
      value_template: '{{ states("input_select.presence_jalynne_status") }}'