- platform: template
  sensors:
    location_away_wayne:
      friendly_name: "Wayne's Away Location"
      value_template: >-
        {% if is_state("device_tracker.phone_wayne", "Wayne Work") %}
          Work
        {% elif states("device_tracker.phone_wayne") != 'home' and states("device_tracker.phone_wayne") != 'not_home' %}
          {{ states("device_tracker.phone_wayne") }}
        {% endif %}
    presence_wayne_status:
      friendly_name: "Wayne"
      value_template: '{{ states("input_select.presence_wayne_status") }}'

    location_away_jenn:
      friendly_name: "Jenn's Away Location"
      value_template: >-
        {% if is_state("device_tracker.phone_jenn", "Jenn Work") %}
          Work
        {% elif states("device_tracker.phone_jenn") != 'home' and states("device_tracker.phone_jenn") != 'not_home' %}
          {{ states("device_tracker.phone_jenn") }}
        {% endif %}
    presence_jenn_status:
      friendly_name: "Jenn"
      value_template: '{{ states("input_select.presence_jenn_status") }}'

    location_away_kale:
      friendly_name: "Kale's Away Location"
      value_template: >-
        {% if states("device_tracker.phone_kale") != 'home' and states("device_tracker.phone_kale") != 'not_home' %}
          {{ states("device_tracker.phone_kale") }}
        {% endif %}
    presence_kale_status:
      friendly_name: "Kale"
      value_template: '{{ states("input_select.presence_kale_status") }}'

    location_away_jalynne:
      friendly_name: "Jalynne's Away Location"
      value_template: >-
        {% if states("device_tracker.phone_jalynne") != 'home' and states("device_tracker.phone_jalynne") != 'not_home' %}
          {{ states("device_tracker.phone_jalynne") }}
        {% endif %}
    presence_jalynne_status:
      friendly_name: "Jalynne"
      value_template: '{{ states("input_select.presence_jalynne_status") }}'
