## Automations to run on startup
- id: ha_start
  initial_state: 'on'
  alias: 'Automations on restart'
  # deprectated in 0.110 #hide_entity: true
  trigger:
     platform: homeassistant
     event: start
  action:     
    - service: frontend.set_theme
      data_template:
        name: '{{ states("input_select.ha_themes")}}'
    - service: input_boolean.turn_off             #zwave delayed automations
      entity_id: 'input_boolean.allow_automation_execution'
    - service: rest_command.google_cast_save_input_selects     #input_select.set_options for all Radio Station Preset selections
    - service: input_select.select_option         #Set saved radio station presets
      data_template: 
        entity_id: input_select.radio_station_p1
        option: '{{ states("input_text.radio_station_p1") }}'
    - service: input_select.select_option         #Set saved radio station presets
      data_template: 
        entity_id: input_select.radio_station_p2
        option: '{{ states("input_text.radio_station_p2") }}'
    - service: input_select.select_option         #Set saved radio station presets
      data_template:
        entity_id: input_select.radio_station_p3
        option: '{{ states("input_text.radio_station_p3") }}'
    - service: input_select.select_option         #Set saved radio station presets
      data_template: 
        entity_id: input_select.radio_station_p4
        option: '{{ states("input_text.radio_station_p4") }}'
    - delay: 10
    - service: automation.turn_on                #re-enable Front Door Lock notifications, take a bit for z-wave to reconnect on startup
      data:
        entity_id:
          - automation.front_door_lock_problem
          - automation.front_door_lock_problem_cleared
          #Shouldn't be needed - moved to Zwave_loaded_Start_System - automation.front_door_lock_problem
          #If not re-disable - automation.front_door_lock_problem_cleared
    - service: input_boolean.turn_on    
      entity_id: input_boolean.ha_startup   #startup routines finished          

- alias: Zwave_loaded_Start_System
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - service: script.turn_on
      entity_id: script.system_cleanup      

- alias: theme_change
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:  input_select.ha_themes
  action:
    - service: frontend.set_theme
      data_template:
        name: '{{ states("input_select.ha_themes")}}'
