- alias: Notify Garbage Day Tomorrow
  initial_state: 'on'
  trigger:  
    - platform: time
      at: '17:00:00'
    - platform: time
      at: '18:00:00'
    - platform: time
      at: '19:00:00'
  condition:
    - condition: template
      value_template: '{{ is_state("sensor.calendar_garbage_day", "Garbage Day (Tomorrow)") }}'
  action:
    - service: script.notify_garbage_day_tomorrow_wayne
    - service: script.notify_garbage_day_tomorrow_jenn
    - service: script.notify_garbage_day_tomorrow_kale
    - service: script.notify_garbage_day_tomorrow_jalynne

- alias: '[Notify Garbage Day Tomorrow - Action] Remind'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: garbage_day_tomorrow_remind
  action:
    - service: >
        notify.mobile_app_phone_{% if trigger.event.context["user_id"] == "c9ce4686a1b642fc9acb4a8b59181499" %}wayne
        {% elif trigger.event.context["user_id"] == "52011960541f4ae3872b4f7eded76992" %}jenn
        {% elif trigger.event.context["user_id"] == "kalesuseridstring" %}kale
        {% else %}jalynne{% endif %}
      data:
        message: clear_notification
        data:
          tag: garbage_day_tomorrow

- alias: '[Notify Garbage Day Tomorrow - Action] Cancel'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: garbage_day_tomorrow_cancel
  action:
    - service: input_boolean.turn_off
      data_template:    
        entity_id: >
          input_boolean.notification_curbside_pickup_{% if trigger.event.context["user_id"] == "c9ce4686a1b642fc9acb4a8b59181499" %}wayne_phone
          {% elif trigger.event.context["user_id"] == "52011960541f4ae3872b4f7eded76992" %}jenn_phone
          {% elif trigger.event.context["user_id"] == "kalesuseridstring" %}kale_phone
          {% else %}jalynne_phone{% endif %}
    - service: >
        notify.mobile_app_phone_{% if trigger.event.context["user_id"] == "c9ce4686a1b642fc9acb4a8b59181499" %}wayne
        {% elif trigger.event.context["user_id"] == "52011960541f4ae3872b4f7eded76992" %}jenn
        {% elif trigger.event.context["user_id"] == "kalesuseridstring" %}kale
        {% else %}jalynne{% endif %}
      data:
        message: clear_notification
        data:
          tag: garbage_day_tomorrow

- alias: Notify Garbage Day Tomorrow Last
  initial_state: 'on'
  trigger:  
    - platform: time
      at: '20:00:00'
  condition:
    - condition: template
      value_template: '{{ is_state("sensor.calendar_garbage_day", "Garbage Day (Tomorrow)") }}'      
  action:
    - service: script.notify_garbage_day_tomorrow_last_wayne
    - service: script.notify_garbage_day_tomorrow_last_jenn
    - service: script.notify_garbage_day_tomorrow_last_kale
    - service: script.notify_garbage_day_tomorrow_last_jalynne
    - service: homeassistant.turn_on           #turn on all notifications for next garbage day
      entity_id: group.notification_curbside_pickup

- alias: Garbage Day Today
  initial_state: 'on'
  trigger:  
    - platform: time
      at: '07:00:00'
  condition:
    - condition: state
      entity_id: calendar.curbside_pickup_garbage_day
      state: 'on'
  action:
    - service: notify.bilger_parents
      data_template:
        title: "Curb side pickup is this morning."
        message: "Be sure to put out the garbage and recycling!"
        data:   
          tag: garbage_day_today              #not really needed
          icon_url: local/photos/notify_garbage_recycling.png
    - service: homeassistant.turn_on           #ensure all notifications on for next garbage day
      entity_id: group.notification_curbside_pickup

