- platform: universal
  name: Bedroom Universal
  children:
    - media_player.bedroom_plex
    - media_player.bedroom_tv_plex
    - media_player.bedroom_androidtv
    - media_player.bedroom_plex_firetv
    - media_player.bedroom_chromecast
    - media_player.bedroom_roku
  commands:
    volume_up:
      service: switch.turn_on
      data:
        entity_id: switch.bedroom_tv_volume_up
    volume_down:
      service: switch.turn_on
      data:
        entity_id: switch.bedroom_tv_volume_down
    volume_mute:
      service: switch.turn_on
      data:
        entity_id: switch.bedroom_tv_volume_mute
