- platform: universal
  name: Dining Room Plex
  children:
    - media_player.dining_room_plex
    - media_player.dining_room_androidtv_plex
    - media_player.dining_room_roku_plex
    - media_player.dining_room_tv_plex

- platform: universal
  name: Deck TV
  children:
    - media_player.deck_chromecast_plex
    - media_player.deck_chromecast
