homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: chohqueo4tuo8ohThoosh9bahsohVaevooChaenohxahkebuo4Ekachua5peesoh
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_10427093f75fec11aef72e5f25bfaa52-if00-port0
frontend:
  port: 8099
devices:
  '0x000b57fffe8d1636':
    friendly_name: Kitchen Island Dimmer
  '0x000b57fffe94f7f9':
    friendly_name: Kitchen Island 1
  '0x000b57fffe9647c3':
    friendly_name: Kitchen Island 2
  '0x000b57fffe8d1dad':
    friendly_name: Kitchen Island 3
  '0x000b57fffe2f0876':
    friendly_name: Jenn Bedroom Light
  '0x000b57fffe149fed':
    friendly_name: Theatre Dimmer
  '0x000b57fffe8caa58':
    friendly_name: Theatre FL
  '0x000b57fffe94f7d0':
    friendly_name: Theatre FR
  '0x000b57fffe8ca18c':
    friendly_name: Theatre RL
  '0x000b57fffe964a31':
    friendly_name: Theatre RR
  '0x000b57fffe14c6a3':
    friendly_name: Family Room Dimmer
  '0x000b57fffe30f74c':
    friendly_name: Family Room 1
  '0x000b57fffe9c69d6':
    friendly_name: Family Room 2
  '0x000b57fffe4c81e4':
    friendly_name: Couch Lamp
groups:
  '1':
    friendly_name: Kitchen Island Lights
    devices:
      - 0x000b57fffe94f7f9/1
      - 0x000b57fffe9647c3/1
      - 0x000b57fffe8d1dad/1
  '2':
    friendly_name: Family Room Light
    devices:
      - 0x000b57fffe30f74c/1
      - 0x000b57fffe9c69d6/1
  '3':
    friendly_name: Theatre Lights
    devices:
      - 0x000b57fffe8caa58/1
      - 0x000b57fffe94f7d0/1
      - 0x000b57fffe8ca18c/1
      - 0x000b57fffe964a31/1
  '4':
    friendly_name: Theatre Lights Front
    devices:
      - 0x000b57fffe8caa58/1
      - 0x000b57fffe94f7d0/1
  '5':
    friendly_name: Theatre Lights Rear
    devices:
      - 0x000b57fffe8ca18c/1
      - 0x000b57fffe964a31/1
